### ISSUE TITLE
Variable 'video' referenced before assignment

### ISSUE THREAD

**Issue by BrutuZ** [pannal/Sub-Zero.bundle#102]
```
2015-12-12 18:35:28,203 (3ff8) :  INFO (logkit:16) - enzyme.mkv: Reading Segment element
2015-12-12 18:35:28,247 (3ff8) :  INFO (logkit:16) - enzyme.parsers.ebml.core: MasterElement EBML 6 ignored
2015-12-12 18:35:28,249 (3ff8) :  INFO (logkit:16) - enzyme.parsers.ebml.core: Maximum level 0 reached for children of MasterElement Segment
2015-12-12 18:35:28,250 (3ff8) :  INFO (logkit:16) - enzyme.mkv: Reading SeekHead element
2015-12-12 18:35:28,250 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Seek with size 12
2015-12-12 18:35:28,252 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Seek with size 12
2015-12-12 18:35:28,252 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Seek with size 14
2015-12-12 18:35:28,253 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Seek with size 14
2015-12-12 18:35:28,253 (3ff8) :  INFO (logkit:16) - enzyme.mkv: Processing element Info from SeekHead at position 4135
2015-12-12 18:35:28,255 (3ff8) :  INFO (logkit:16) - enzyme.mkv: Processing element Tracks from SeekHead at position 4282
2015-12-12 18:35:28,256 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement TrackEntry with size 138
2015-12-12 18:35:28,257 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Video with size 19
2015-12-12 18:35:28,259 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement TrackEntry with size 83
2015-12-12 18:35:28,262 (3ff8) :  DEBUG (logkit:13) - enzyme.parsers.ebml.core: Loading child elements for MasterElement Audio with size 9
2015-12-12 18:35:28,263 (3ff8) :  DEBUG (logkit:13) - enzyme.mkv: Element SeekHead ignored
2015-12-12 18:35:28,263 (3ff8) :  DEBUG (logkit:13) - enzyme.mkv: Element Cues ignored
2015-12-12 18:35:28,265 (3ff8) :  ERROR (logkit:22) - subliminal_patch.patch_video: Parsing video with enzyme has gone terribly wrong: Traceback (most recent call last):
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\patch_video.py", line 133, in scan_video
    video.resolution = '%dp' % video_track.height
UnboundLocalError: local variable 'video' referenced before assignment

2015-12-12 18:35:28,266 (3ff8) :  CRITICAL (core:574) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.3.20.422)', called with guid 'com.plexapp.agents.thetvdb://81751/1/40?lang=en' (most recent call last):
  File "bundles-release/Framework.bundle-dist-ninja/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 294, in update
    scanned_parts = scanParts(parts, kind=self.agent_type)
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 132, in scanParts
    scanned_video = scanVideo(part["video"], ignore_all=force_refresh, hints=hints)
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\__init__.py", line 163, in scanVideo
    return subliminal.video.scan_video(part.file, subtitles=external_subtitles, embedded_subtitles=embedded_subtitles, hints=hints or {})
  File "G:\Plex\Data\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\patch_video.py", line 195, in scan_video
    return video
UnboundLocalError: local variable 'video' referenced before assignment

2015-12-12 18:35:28,269 (3ff8) :  DEBUG (model:229) - Serializing to G:\Plex\Data\Plex Media Server\Metadata\TV Shows\b\d565f3f98604ce27ddefbe205b4bca7a4b5d11f.bundle\Contents\com.plexapp.agents.subzero\Info.xml
2015-12-12 18:35:28,272 (3ff8) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by infernix** [comment]
Seeing this too:
```
2015-12-24 16:42:08,192 (7f2a2affd700) :  ERROR (logger:36) - subliminal_patch.patch_video: Parsing video with enzyme has gone terribly wrong: Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_video.py", line 133, in scan_video
    video.resolution = '%dp' % video_track.height
UnboundLocalError: local variable 'video' referenced before assignment

2015-12-24 16:42:08,192 (7f2a2affd700) :  CRITICAL (agentkit:1067) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.3.20.422)', called with guid 'com.plexapp.agents.thetvdb://289574/1/61?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-344f193/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 294, in update
    scanned_parts = scanParts(parts, kind=self.agent_type)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 132, in scanParts
    scanned_video = scanVideo(part["video"], ignore_all=force_refresh, hints=hints)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 163, in scanVideo
    return subliminal.video.scan_video(part.file, subtitles=external_subtitles, embedded_subtitles=embedded_subtitles, hints=hints or {})
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_video.py", line 195, in scan_video
    return video
UnboundLocalError: local variable 'video' referenced before assignment
```

**Comment by pannal** [comment]
Confirmed, will be fixed in the next version. Which version are you running and what kind of media is this? Guessit is failing to guess the filename.

**Comment by infernix** [comment]
@pannal master as of a few days ago. Media is an mkv tv show with YYYY-MM-DD episodes.

**Comment by pannal** [comment]
Please try the current master, I fixed that issue before in a separate branch, together with some TV series matching improvements. It's merged now.

**Comment by infernix** [comment]
So far so good, will update if it reoccurs
