### ISSUE TITLE
Podnapisi Provider Error

### ISSUE THREAD

**Issue by JigSawFr** [pannal/Sub-Zero.bundle#113]
When searching subtitles for "Marvel's Daredevil", Podnapisi is crashing, so discarded.
Here is the log:
```
016-01-12 13:39:07,077 - com.plexapp.agents.subzero       (7f07eabe0700) :  ERROR (logger:34) - subliminal_patch.patch_providers.addic7ed: No show id found for u"Marvel's Daredevil" ({'country': None, 'year': None})
2016-01-12 13:39:07,078 - com.plexapp.agents.subzero       (7f07eabe0700) :  INFO (logger:38) - subliminal_patch.patch_provider_pool: Listing subtitles with provider 'podnapisi' and languages set([<Language [fr]>, <Language [en]>])
2016-01-12 13:39:07,079 - com.plexapp.agents.subzero       (7f07eabe0700) :  INFO (logger:38) - subliminal.api: Initializing provider podnapisi
2016-01-12 13:39:07,079 - com.plexapp.agents.subzero       (7f07eabe0700) :  INFO (logger:38) - subliminal.providers.podnapisi: Searching subtitles {u'sK': u"Marvel's Daredevil", u'sTE': 13, u'sXML': 1, u'sTS': 1, u'sL': 'fr'}
2016-01-12 13:39:07,246 - com.plexapp.agents.subzero       (7f07eabe0700) :  ERROR (logger:34) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'podnapisi', discarding it, because of: Traceback (most recent call last):
  File "/config/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 179, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/config/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/podnapisi.py", line 157, in list_subtitles
    episode=video.episode, year=video.year)]
  File "/config/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/podnapisi.py", line 106, in query
    xml = etree.fromstring(self.session.get(self.server_url + 'search/old', params=params, timeout=10).content)
  File "lxml.etree.pyx", line 2743, in lxml.etree.fromstring (src/lxml/lxml.etree.c:52665)
  File "parser.pxi", line 1573, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:79932)
  File "parser.pxi", line 1452, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:78774)
  File "parser.pxi", line 960, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:75389)
  File "parser.pxi", line 564, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:71739)
  File "parser.pxi", line 645, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:72614)
  File "parser.pxi", line 585, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:71955)
XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8
```

**Comment by pannal** [comment]
The search for "Marvel's Daredevil" doesn't work on podnapisi, but that's unrelated. The search doesn't error out. Have you been refreshing your whole library before and perhaps been shut out of podnapisi for that day?
