### ISSUE TITLE
Opensubtitles weird error

### ISSUE THREAD

**Issue by jbreuer95** [pannal/Sub-Zero.bundle#122]
For some reason opensubtitles isnt working anymore and im not getting any subtitles for my movies ?
`WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x37d56e0>
2016-01-28 10:49:12,269 (7f89cbdcb700) :  ERROR (logger:38) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'opensubtitles', discarding it, because of: Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 179, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/api.py", line 62, in __getitem__
    provider.initialize()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/opensubtitles.py", line 44, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', 'subliminal v%s' % get_version(__version__)))
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known`

**Comment by pannal** [comment]
This seems like the OpenSubtitles API wasn't reachable at that point. Something either with your DNS, routing, or they really were down.
