### ISSUE TITLE
Some series are not being recognized

### ISSUE THREAD

**Issue by kolyagora** [pannal/Sub-Zero.bundle#210]
I'm getting errors for some series which have year in their name, i.g. [Mars (2016)](http://thetvdb.com/?tab=series&id=316345) and [The Grand Tour (2016)](http://thetvdb.com/?tab=series&id=314087).

```
2016-11-26 23:45:14,489 (-c7cd470) :  ERROR (logger:38) - subliminal_patch.patch_providers.tvsubtitles: No show id found for 'Mars (2016)' ({'year': None})
2016-11-26 23:48:43,847 (-c4df470) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Series not found in show ids, attempting search
2016-11-26 23:48:43,848 (-c4df470) :  ERROR (logger:38) - subliminal_patch.patch_providers.addic7ed: No show id found for 'The Grand Tour (2016)' ({'country': None, 'year': None})
2016-11-26 23:48:45,926 (-c4df470) :  ERROR (logger:38) - subliminal_patch.patch_providers.tvsubtitles: No show id found for 'The Grand Tour (2016)' ({'year': None})
2016-11-26 23:48:57,067 (-bd82470) :  WARNING (plex_media:107) - File could not be guessed by subliminal
2016-11-26 23:49:19,221 (-cabb470) :  WARNING (plex_media:107) - File could not be guessed by subliminal
2016-11-26 23:49:24,771 (-b7a6470) :  WARNING (logger:36) - subliminal_patch.patch_providers.addic7ed: Series not found in show ids, attempting search
2016-11-26 23:49:24,772 (-b7a6470) :  ERROR (logger:38) - subliminal_patch.patch_providers.addic7ed: No show id found for 'The Grand Tour (2016)' ({'country': None, 'year': None})
2016-11-26 23:49:27,018 (-b7a6470) :  ERROR (logger:38) - subliminal_patch.patch_providers.tvsubtitles: No show id found for 'The Grand Tour (2016)' ({'year': None}) 
```

**Comment by pannal** [comment]
Yep, introduced that bug recently. Will be fixed

**Comment by pannal** [comment]
fixed in next release

**Comment by kolyagora** [comment]
I think it may be related, so I continue here.
After updating to 1.4.16.822 I get this:
`2016-12-05 13:31:49,312 (-b7ee470) :  ERROR (logger:34) - subliminal_patch.patch_providers.tvsubtitles: No show id found for u'MARS' ({'year': None}) `
However, the show exists: http://www.tvsubtitles.net/tvshow-2120-1.html

**Comment by pannal** [comment]
I'll need the full logs to that, attached, please.

**Comment by kolyagora** [comment]
I've set the loglevel to DEBUG and initiated refresh but got no errors. I'll come back with the full log if I see it again.

**Comment by kolyagora** [comment]
The log is there: [com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/634997/com.plexapp.agents.subzero.zip)
The error I've mentioned earlier is at line 3019.

**Comment by kauanmocelin** [comment]
This bug has fixed? I am having this problem still.

`2018-04-06 23:41:42,843 (63fff470) :  ERROR (logger:38) - subliminal.providers.tvsubtitles: No show id found for u'Avatar: The Last Airbender' ({'year': 2005})
2018-04-06 23:42:03,902 (637ff470) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 98, in __getitem__
    provider = provider_registry[name](**self.provider_configs.get(name, {}))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 175, in __init__
    raise ConfigurationError('UNRAR tool not available')
ConfigurationError: UNRAR tool not available`

**Comment by kauanmocelin** [comment]
I'm using raspbian stretch, i tryed to install a "unrar" following this link http://www.nburles.co.uk/raspberrypi/installing-unrar-on-the-raspberry-pi but doesn't worked.

Can u help to install? In this link #311 don't exists information about linux installation.

**Comment by pannal** [comment]
This will be fixed in the upcoming version, hopefully for your OS, too.

Can you execute `unrar` as the user that runs Plex?

**Comment by kauanmocelin** [comment]
Now seems the unrar error is resolved. But i receive error 503, i downloaded manually this UnitedTeam5021269f7419949df1eafa5575e69513.rar and the subtitles seems ok. Look my log:

`2018-04-07 01:32:01,069 (6d27e470) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 502, in list_subtitles
    self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 460, in query
    self.download_archive(a)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 419, in download_archive
    raise_for_status(r)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/legendastv.py", line 522, in raise_for_status
    r.raise_for_status()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Service Unavailable for url: http://f.legendas.tv/u/UnitedTeam5021269f7419949df1eafa5575e69513.rar`

**Comment by pannal** [comment]
That's just legendas returning an error code, nothing related to SZ.

**Comment by kauanmocelin** [comment]
@pannal return of py command:

('Linux', 'raspi', '4.14.30-v7+', '#1102 SMP Mon Mar 26 16:45:49 BST 2018', 'armv7l')
