### ISSUE TITLE
Sub-Zero (HEAD) won't start after upgrading to Plex 1.4.2

### ISSUE THREAD

**Issue by diligiant** [pannal/Sub-Zero.bundle#244]
here is the log file hoping this helps.

[com.plexapp.agents.subzero_log.txt](https://github.com/pannal/Sub-Zero.bundle/files/790384/com.plexapp.agents.subzero_log.txt)

**Comment by pannal** [comment]
Hmm. I don't think this is SZ related.

`2017-02-21 15:15:53,819 (700002842000) :  ERROR (messaging:49) - Unable to reach the system bundle.` indicates an internal problem for me. Any idea @ukdtom ?

**Comment by diligiant** [comment]
The strange thing being that it only affects "you". Webtools and Trakt are just fine. I'll dig further.

**Comment by pannal** [comment]
Yeah that's totally possible, as SZ accesses the Plex api as soon as the plugin is started to figure out information about your setup. 

It's quite likely that trakt and webtools don't do that.

**Comment by ukdtom** [comment]
WebTools does access it.

Think PMS and System logs would be handy here

**Comment by pannal** [comment]
My PMS auto update just updated to 1.4.2, and SZ is still working fine. Did you try reinstalling the PMS?

**Comment by diligiant** [comment]
I just did matrix testing : 142 with 2/20 db, 134 with 2/20 and 2/21 dbs and the problem was still there. So I updated 134 to 142 and it works. Don't ask me, I don't know ;( I'll keep an eye as recently I noticed SZ was gone but a simple restart "forced' it back. I was lazy and did not investigate. I will now.

**Comment by diligiant** [comment]
It's back! @ukdtom, I included PMS.log (looks meaningless to me) too. I checked /var/log/system.log and there are no entries around the time of the problem.

[Plex Media Server_log.txt](https://github.com/pannal/Sub-Zero.bundle/files/793874/Plex.Media.Server_log.txt)
[com.plexapp.agents.subzero_log.txt](https://github.com/pannal/Sub-Zero.bundle/files/793875/com.plexapp.agents.subzero_log.txt)

**Comment by ukdtom** [comment]
I was talking about the plex system log ;-)

But when said.....

You are having either performance problems, or database issues here:

`Feb 22, 2017 15:55:38.782 [0x700001c62000] WARN - SLOW QUERY: It took 2700.000000 ms to retrieve 3 items.`

So IMHO not related to SZ, but to your PMS, or weak HW lacking resources

**Comment by ukdtom** [comment]
And when said....Try for a start and optimize the database

https://support.plex.tv/hc/en-us/articles/200392106

**Comment by diligiant** [comment]
Thanx. Did that yesterday and today (slow query is gone but problem persists). If what you say (performance) is true, that's worrysome as this is a dedicated i7/4 cores with 16Gig of RAM + thunderbolt RAID! Do I need a cray ? ;)

You said that you access the same resources. Any idea why this doesn't fail ? During the post-optimize launch, the same error stack frame starts a little earlier
`017-02-22 17:51:26,096 (7fff941693c0) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json`
`2017-02-22 17:51:26,097 (7fff941693c0) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.agents.subzero`
`2017-02-22 17:51:26,140 (7fff941693c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/sections'`
`2017-02-22 17:51:46,143 (7fff941693c0) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):`
`    File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
`

**Comment by ukdtom** [comment]
As a bare minimum, a Cray is not needed, but preferred ;-)

Sadly not a Mac owner here, so no way of testing, but here's what I would do:

1. Remove SZ
2. Delete `Library/Plex Media Server/Plug-in Support/Caches/com.plexapp.agents.subzero` directory if it exists
3. Delete `Library/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.subzero` directory if it exists
4. Delete the file named `Library/Plex Media Server/Plug-in Support/Preferences/com.plexapp.agents.subzero.xml` if it exists

With above, all traces of SZ is gone

Then reapply latest PMS version (PP version in your case)
Power is up, and check PMS logs for errors, and if non, reapply SZ from the channels menu, and reconfigure

/T

**Comment by pannal** [comment]
I seriously can't imagine what causes this.

**Comment by ukdtom** [comment]
Only a corruption somewhere, IMHO, and as such why I suggested a complete removal and reapply of SZ, as well as a reapply of PMS

**Comment by diligiant** [comment]
@ukdtom what do you mean by "reapply PMS" ?
@pannal, I'm gonna follow @ukdtom suggestion and let you know (I've had problems with SZ in the past that were "solved" by restarting). I wonder how large is Plex test db ;)

**Comment by ukdtom** [comment]
I mean put on top of already existing one, to make sure framework python files are reapplied

> Then reapply latest PMS version (PP version in your case)

**Comment by diligiant** [comment]
@ukdtom on mac, install is a simple drag&drop so downgrade to 134 and upgrade to 142 from within ?

**Comment by ukdtom** [comment]
No idea here....As said, not a Mac dude.....On QNAP, simply apply on top. On Windows, uninstall and reinstall. On Suse, run the RPM with an -UHV param... But Apple, clueless sadly...

Might wanna ask in the forums

**Comment by ukdtom** [comment]
@diligiant @pannal 

Disregard.....

New user, also on Ubuntu, having same issue as you, but with WebTools

from his system log:

`2017-02-21 19:11:26,731 (7f7a03fff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/sections'
2017-02-21 19:11:26,732 (7f7a44d79700) :  CRITICAL (storeservice:510) - Error info (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/System.bundle/Contents/Code/storeservice.py", line 495, in update
    log_msg = "Updated information for plug-in '%s' (class: %s) to a stable version"
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
`

So looks like a general problem, and alerting Plex here

**Comment by ukdtom** [comment]
And @diligiant Would still love to see your system log!

**Comment by diligiant** [comment]
@ukdtom /var/log/system.log ? There is really nothing here. The plex dev rightly push in PMS.log instead of messing with system.log ;)
And, of course, I restarted to send you everything (including Webtools) and no fatal error this time…
"Only" tons of
`2017-02-22 20:37:16,679 (70000fad1000) :  ERROR (tasks:362) - Couldn't get item info for 610626
`
and
`2017-02-22 20:37:28,954 (70000fad1000) :  ERROR (background:125) - Scheduler: Something went wrong when running FindBetterSubtitles: Traceback (most recent call last):`
`  File "/Users/frederic/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/background.py", line 123, in run_task`
`    task.run()`
`  File "/Users/frederic/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 379, in run`
`    for part_id, languages in parts.iteritems():`
`RuntimeError: dictionary changed size during iteration`

**Comment by ukdtom** [comment]
Nope.....Plex System log.....

In PMS, select settings/help, and grap logs from that

**Comment by diligiant** [comment]
your wish is my command ;)
[Plex Media Server Logs_2017-02-22_20-47-08.zip](https://github.com/pannal/Sub-Zero.bundle/files/794636/Plex.Media.Server.Logs_2017-02-22_20-47-08.zip)
[com.plexapp.agents.subzero_log.txt](https://github.com/pannal/Sub-Zero.bundle/files/794637/com.plexapp.agents.subzero_log.txt)
[com.plexapp.plugins.WebTools_log.txt](https://github.com/pannal/Sub-Zero.bundle/files/794638/com.plexapp.plugins.WebTools_log.txt)

**Comment by ukdtom** [comment]
Thanks, and your system log is full of timeouts:

`2017-02-22 15:52:57,460 (7000047ef000) :  CRITICAL (runtime:1128) - Exception in thread named 'refresh_servers' (most recent call last):
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1126, in _start_thread
    f(*args, **kwargs)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/System.bundle/Contents/Code/peerservice.py", line 169, in refresh_servers
    servers_el = self.get_servers_el()
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/System.bundle/Contents/Code/peerservice.py", line 165, in get_servers_el
    return XML.ElementFromURL('http://127.0.0.1:32400/servers', cacheTime = 0)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 344, in ElementFromURL
    method=method,
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-ab906953b/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>`

So info for Plex here

**Comment by diligiant** [comment]
@ukdtom you sent them ?

**Comment by ukdtom** [comment]
Nope, I asked Plex to take a peak here ;-)

**Comment by ukdtom** [comment]
@diligiant 

Plex ask:

`could you please ask for debug logging to enabled on the server and restart the server and then get matching set of logs, best to zip all logs and PMS Plugin Logs so that one gets a better picture and the extent of the issues`

In above, if you could zip the entire log directory, incl. sub directory, it would be great.
If you want be even greater, then switch into debug mode on PMS, power it down, and then delete the entire contents of the log directory, incl. sub dir, before powering up again

**Comment by diligiant** [comment]
A fresh set of logs!
[pms.zip](https://github.com/pannal/Sub-Zero.bundle/files/794750/pms.zip)

(I'll be AFK in 4h for 36h)

**Comment by ukdtom** [comment]
NP, on GMT+1 here ;-)

**Comment by diligiant** [comment]
as well

**Comment by ukdtom** [comment]
@diligiant 

What's up with the 127.0.0.54 address been detected?

**Comment by diligiant** [comment]
dnscrypt

**Comment by ukdtom** [comment]
Try and disable that for a short test, and then restart PMS

**Comment by diligiant** [comment]
ok but it's been on for almost a year…

same shit ;(

**Comment by ukdtom** [comment]
Ack

Will tell Plex

**Comment by ukdtom** [comment]
Did you alter your host file?

**Comment by diligiant** [comment]
no

**Comment by diligiant** [comment]
can you tell me what you have in mind ? That might help me pop something up. I've been doing some debugging on my 21.co bitcoin computer so my python is getting better ;)

**Comment by ukdtom** [comment]
Sadly was simply grasping a straw here, (Not Plex, but me), but the Q about dual loopback address was from Plex though....

So far, the conclusion is, that this sadly isn't related to my WebTools issue, but instead a local issue in your setup.

And so far completely clueless here.

When said, bedtime here, since workday tomorrow, so will not return for the next 12 hours @ least

Sorry

**Comment by diligiant** [comment]
it's been the same setup for months and being a software engineer myself, I find this a little "easy" ;) Can you ask them to get in touch directly so we can find the problem ?

This product deserves to be more bulletproof

**Comment by ukdtom** [comment]
Not going to happen, since not the way the Plex support model work....

In fact, since this isn't a SZ issue, you should be posting in the Forum threads!

**Comment by diligiant** [comment]
ok. Any @name I should mention for the discussion to be picked up were you paused it ?

**Comment by pannal** [comment]
@ukdtom how exactly does the Plex support system for stuff like that work? I mean if I really find a bug in system.bundle, who would I tell? I can't imagine them browsing the public forums tbh.

**Comment by ukdtom** [comment]
Nope ;-)

And bed time for now, so stepping out

**Comment by ukdtom** [comment]
ANd when said, I'm a Plex Ninja...

And as such, your contact...

Forum NickName is dane22

**Comment by ukdtom** [comment]
https://forums.plex.tv/discussion/259784/1-4-2-crash-bug-messed-up-server-since-1-4-2-upgrade

Issue closed

**Comment by diligiant** [comment]
Hi @ukdtom, sa2000 from the plex team would like you to take a look at [forum](https://forums.plex.tv/discussion/259784/1-4-2-crash-bug-messed-up-server-since-1-4-2-upgrade#latest) as I might have encountered a bug in plex but he "needs" your expertise.
