### ISSUE TITLE
ERROR (logger:36) - subliminal_patch.patch_provider_pool: Provider 'opensubtitles' timed out, discarding it

### ISSUE THREAD

**Issue by chmercesmoreira** [pannal/Sub-Zero.bundle#261]
Hello, I'd like to know what this error message mean:
`ERROR (logger:36) - subliminal_patch.patch_provider_pool: Provider 'opensubtitles' timed out, discarding it`

The plugin is not downloading any subtitle.

EDIT
I'm getting this message as well:
`ERROR (logger:36) - subliminal.api: Provider 'opensubtitles' timed out, improperly terminated`

**Comment by pannal** [comment]
Please refer to the wiki on how to produce log files, then attach them here.

**Comment by pannal** [comment]
But it seems as though opensubtitles currently isn't working for you. That happens sometimes.

**Comment by chmercesmoreira** [comment]
I just want someone else to test and see if their server is down ;-(((

**Comment by chmercesmoreira** [comment]
Look I got a new log:
`ERROR (logger:34) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'opensubtitles', discarding it, because of: Traceback (most recent call last):
  File "/var/lib/plex/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 179, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/var/lib/plex/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/api.py", line 62, in __getitem__
    provider.initialize()
  File "/var/lib/plex/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/opensubtitles.py", line 88, in initialize
    lambda: checked(
  File "/var/lib/plex/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/mixins.py", line 34, in retry
    return f()
  File "/var/lib/plex/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/opensubtitles.py", line 89, in <lambda>
    self.server.LogIn(self.username, self.password, 'eng', 'subliminal v%s' % get_version(__version__))
  File "/opt/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/opt/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/opt/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>`

**Comment by chmercesmoreira** [comment]
It makes sense now:

![](http://i.imgur.com/V1m4zDq.png)
