### ISSUE TITLE
Sub-Zero 2.0.24.1565 doesn't work with Nvidia shield Plex

### ISSUE THREAD

**Issue by valkhyr1** [pannal/Sub-Zero.bundle#314]
Sub-Zero 2.0.24.1565 doesn't work with a nvidia shield plex server 
After the upgrade I couldn't open the settings, after reinstall I don't see Sub-Zero at all.

2017-07-07 22:30:13,603 (2003fada98) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 3886b5c (Thu Jun 22 13:26:18 UTC 2017)
2017-07-07 22:30:13,604 (2003fada98) :  DEBUG (core:361) - Using the elevated policy
2017-07-07 22:30:13,604 (2003fada98) :  DEBUG (core:450) - Starting runtime component.
2017-07-07 22:30:13,608 (2003fada98) :  DEBUG (core:450) - Starting caching component.
2017-07-07 22:30:13,608 (2003fada98) :  DEBUG (core:450) - Starting data component.
2017-07-07 22:30:13,609 (2003fada98) :  DEBUG (core:450) - Starting networking component.
2017-07-07 22:30:13,610 (2003fada98) :  DEBUG (networking:284) - Loaded HTTP cookies
2017-07-07 22:30:13,611 (2003fada98) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2017-07-07 22:30:13,612 (2003fada98) :  DEBUG (core:450) - Starting localization component.
2017-07-07 22:30:13,613 (2003fada98) :  INFO (localization:409) - Setting the default locale to en-us
2017-07-07 22:30:13,613 (2003fada98) :  DEBUG (localization:427) - Loaded en strings
2017-07-07 22:30:13,614 (2003fada98) :  DEBUG (core:450) - Starting messaging component.
2017-07-07 22:30:13,614 (2003fada98) :  DEBUG (core:450) - Starting debugging component.
2017-07-07 22:30:13,615 (2003fada98) :  DEBUG (core:450) - Starting services component.
2017-07-07 22:30:13,615 (20074f0450) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.subzero'
2017-07-07 22:30:13,616 (2003fada98) :  DEBUG (core:450) - Starting myplex component.
2017-07-07 22:30:13,618 (2003fada98) :  DEBUG (core:450) - Starting notifications component.
2017-07-07 22:30:13,968 (2003fada98) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.subzero in namespace 'metadata'
2017-07-07 22:30:13,980 (2003fada98) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2017-07-07 22:30:14,021 (2007630450) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2017-07-07 22:30:14,022 (2003fada98) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2017-07-07 22:30:14,023 (2007630450) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2017-07-07 22:30:14,024 (2003fada98) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2017-07-07 22:30:14,026 (2003fada98) :  DEBUG (core:150) - Finished starting framework core
2017-07-07 22:30:14,026 (2003fada98) :  DEBUG (core:560) - Loading plug-in code
2017-07-07 22:30:14,037 (200782a450) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2017-07-07 22:30:14,046 (200782a450) :  DEBUG (core:538) - Machine identifier is c9e1d451e606250ceb9b106cb8ebffdbb8d02fc5
2017-07-07 22:30:14,112 (200782a450) :  DEBUG (core:539) - Server version is 1.7.4.4017-3886b5c85
2017-07-07 22:30:14,196 (2003fada98) :  DEBUG (core:566) - Finished loading plug-in code
2017-07-07 22:30:15,150 (2007630450) :  DEBUG (services:362) - Loaded services
2017-07-07 22:30:15,183 (200772d450) :  DEBUG (services:438) - No shared code to load
2017-07-07 22:30:15,797 (2003fada98) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 20, in <module>
    import support
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/__init__.py", line 4, in <module>
    import config
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/config.py", line 10, in <module>
    import subliminal
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
OSError: [Errno 13] Permission denied

**Comment by pannal** [comment]
Can you attach the whole log? (Just drop the file inside this box)

**Comment by valkhyr1** [comment]
[PMS Plugin Logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1132931/PMS.Plugin.Logs.zip)

**Comment by pannal** [comment]
Hmm, it fails very early. Can you list the permissions of the `/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries` folder and its contents?

**Comment by pannal** [comment]
Also is this a manual installation?

**Comment by valkhyr1** [comment]
No, I installed Sub Zero through the channel installation.

**Comment by pannal** [comment]
OK. Do you know enough to answer my previous question? Or do you need help with that?

**Comment by valkhyr1** [comment]
I must find out how to view the permissions on a andoid tv box. I don't have ssh or ftp access at the moment.

**Comment by valkhyr1** [comment]
Sorry I pushed the wrong button .....

**Comment by pannal** [comment]
Yeah you'll need that kind of insight, definitely. You can enable ADB debugging, though, and use your PC to access the system via ADB.

**Comment by valkhyr1** [comment]
Thanx I will try this later

**Comment by valkhyr1** [comment]
I can't access the data directory with ADB.
1|darcy:/ $ ls /data
ls: /data: Permission denied
I don't have root access on my nvidia shield.

**Comment by pannal** [comment]
I'm still figuring out how to debug this. Please bear with me.

**Comment by pannal** [comment]
I've opened a [cry-for-help thread on the forums regarding this](https://forums.plex.tv/discussion/279548/rooted-nvidia-shield-users-sub-zero-needs-your-help#latest).

**Comment by valkhyr1** [comment]
I have signed up for the NVIDIA Developer Program, I will try to install the SHIELD Developer OS Image.

**Comment by pannal** [comment]
Oh good. But instead you could also unlock and root the system, then re-lock it after we're done.
I guess you'll have to do the same with the developer OS image.

**Comment by valkhyr1** [comment]
darcy:/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries # ls -ltra
total 24
drwx------  3 u0_a62 u0_a62 4096 2017-07-16 13:01 .
drwx------ 34 u0_a62 u0_a62 4096 2017-07-16 13:01 Shared
drwx------  6 u0_a62 u0_a62 4096 2017-07-16 13:01 ..

darcy:/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared # ls -ltra
total 1280
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 pyga
-rw-------  1 u0_a62 u0_a62   6209 2017-07-16 13:01 pyemitter.py
-rw-------  1 u0_a62 u0_a62   4172 2017-07-16 13:01 provider_test.sh
-rw-------  1 u0_a62 u0_a62   3773 2017-07-16 13:01 plex_test.py
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 plex_activity
drwx------  7 u0_a62 u0_a62   4096 2017-07-16 13:01 plex
-rw-------  1 u0_a62 u0_a62 101340 2017-07-16 13:01 pkg_resources.py
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 json_tricks
drwx------  9 u0_a62 u0_a62   4096 2017-07-16 13:01 html5lib
drwx------  5 u0_a62 u0_a62   4096 2017-07-16 13:01 guessit
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 ftfy
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 enzyme
-rw-------  1 u0_a62 u0_a62  16092 2017-07-16 13:01 dumprar.py
-rw-------  1 u0_a62 u0_a62   8938 2017-07-16 13:01 dumbdbm.py
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 dogpile
-rw-------  1 u0_a62 u0_a62    498 2017-07-16 13:01 dbhash.py
drwx------  5 u0_a62 u0_a62   4096 2017-07-16 13:01 dateutil
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 concurrent
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 click
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 chardet
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 certifi
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 bs4
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 babelfish
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 asio
-rw-------  1 u0_a62 u0_a62  89214 2017-07-16 13:01 argparse.py
-rw-------  1 u0_a62 u0_a62  22374 2017-07-16 13:01 appdirs.py
-rw-------  1 u0_a62 u0_a62   2663 2017-07-16 13:01 anydbm.py
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 _markerlib
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 ..
drwx------  5 u0_a62 u0_a62   4096 2017-07-16 13:01 stevedore
-rw-------  1 u0_a62 u0_a62  30098 2017-07-16 13:01 six.py
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 retry
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 requests
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 rebulk
-rw-------  1 u0_a62 u0_a62  86536 2017-07-16 13:01 rarfile.py
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 pytz
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 pysubs2
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 pysrt
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 xdg
drwx------  5 u0_a62 u0_a62   4096 2017-07-16 13:01 wraptor
drwx------  2 u0_a62 u0_a62   4096 2017-07-16 13:01 websocket
drwx------  3 u0_a62 u0_a62   4096 2017-07-16 13:01 wcwidth
-rw-------  1 u0_a62 u0_a62  53344 2017-07-16 13:01 test2.srt
-rw-------  1 u0_a62 u0_a62  50224 2017-07-16 13:01 test.srt
-rw-------  1 u0_a62 u0_a62    688 2017-07-16 13:01 test.py
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 subzero
-rw-------  1 u0_a62 u0_a62    866 2017-07-16 13:01 submod_test.py
drwx------  4 u0_a62 u0_a62   4096 2017-07-16 13:01 subliminal_patch
drwx------  5 u0_a62 u0_a62   4096 2017-07-16 13:01 subliminal
drwx------ 34 u0_a62 u0_a62   4096 2017-07-16 13:01 .

**Comment by pannal** [comment]
Hmm, sadly, nothing interesting as far as I can see.

Are you now able to access the plugin folder of the PMS to manually install plugins? That way we could potentially nail this issue.

**Comment by valkhyr1** [comment]
Yes, I can. I can now access the filesystem with root permissions

**Comment by pannal** [comment]
Great. I will whip up some Debug builds and get back to you.

**Comment by pannal** [comment]
Can you go to the `Application Support\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared` folder and execute `python -c "import subliminal"` and post the output? (If any)

**Comment by valkhyr1** [comment]
1|darcy:/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared # python -c "import subliminal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "subliminal/__init__.py", line 9, in <module>
    import logging
ImportError: No module named logging

**Comment by pannal** [comment]
Can you find a logger package inside the library folders of the PMS installation? Just trying to verify the packaged python doesn't differ.

**Comment by pannal** [comment]
You can also try downloading the last subzero 1.4 release, put it into Dev mode (see wiki) and see if that still works. You'll have to uninstall the official 2.0 first, though.

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/releases/download/1.4.27.980/Sub-Zero.bundle-1.4.27.980.1.zip

**Comment by valkhyr1** [comment]
The last Sub-zero 1.4 release works with my Nvidia shield plex server.

**Comment by pannal** [comment]
Ok. Just to verify: putting 2.0 in Dev mode doesn't?

**Comment by valkhyr1** [comment]
[PMS Plugin Logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1158104/PMS.Plugin.Logs.zip)

**Comment by pannal** [comment]
That log shows output of 1.4.27.980. DId you try installing the latest 2.0 zip afterwards, manually, and putting it into dev mode as well?

**Comment by valkhyr1** [comment]
I did also try to install the latest 2.0 zip en enabled the dev mode. Still the same problem.

[PMS Plugin Logs.zip](https://github.com/pannal/Sub-Zero.bundle/files/1159722/PMS.Plugin.Logs.zip)

**Comment by valkhyr1** [comment]
I see the following error in the file com.plexapp.system.log.
2017-07-19 17:49:42,485 (201e1f0450) :  DEBUG (runtime:88) - Sending packed state data (1135 bytes)
2017-07-19 17:49:42,486 (201e1f0450) :  DEBUG (runtime:924) - Response: [500] 2723 bytes
2017-07-19 17:49:47,403 (201f7f3450) :  INFO (datakit:131) - Saved the dictionary file
2017-07-19 17:49:53,775 (201e1f0450) :  DEBUG (runtime:717) - Handling request GET /system/appstore/apps/com.plexapp.agents.subzero/uninstall
2017-07-19 17:49:53,777 (201e1f0450) :  DEBUG (runtime:49) - Received packed state data (1116 bytes)
2017-07-19 17:49:53,779 (201e1f0450) :  DEBUG (runtime:814) - Found route matching /system/appstore/apps/com.plexapp.agents.subzero/uninstall
2017-07-19 17:49:53,782 (201f6f6450) :  DEBUG (runtime:49) - Received packed state data (1116 bytes)
2017-07-19 17:49:53,782 (201e1f0450) :  DEBUG (runtime:1117) - Created a thread named 'remove_unavailable_agents'
2017-07-19 17:49:53,786 (201e1f0450) :  DEBUG (networking:166) - Requesting 'https://plugins.plex.tv/apps/all.json?frameworkVersion=2.6.3&machineIdentifier=0fdbe3205a3f7c9b9cbcfb0766a77737d0f6b5bc&os=Linux&osVersion=7.0&cpu=aarch64&serverVersion=1.7.4.4017-3886b5c85&systemRevision=3886b5c'
2017-07-19 17:49:53,862 (201e1f0450) :  INFO (storeservice:469) - No beta plugins.
2017-07-19 17:49:53,877 (201e1f0450) :  INFO (installservice:340) - Attempting to uninstall com.plexapp.agents.subzero...
2017-07-19 17:49:53,878 (201e1f0450) :  INFO (installservice:112) - Cleaning up after com.plexapp.agents.subzero (removing /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-in Support/Data/com.plexapp.system/DataItems/Deactivated/com.plexapp.agents.subzero)
2017-07-19 17:49:53,880 (201e1f0450) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/System.bundle/Contents/Code/installservice.py", line 595, in gui_uninstall
    result = self.uninstall(identifier)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/System.bundle/Contents/Code/installservice.py", line 341, in uninstall
    if not self.deactivate(identifier):
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/System.bundle/Contents/Code/installservice.py", line 119, in deactivate
    self.cleanup(identifier)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/System.bundle/Contents/Code/installservice.py", line 113, in cleanup
    Core.storage.remove_tree(inactive_path)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-3886b5c85/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 139, in remove_tree
    shutil.rmtree(path, ignore_errors=False, onerror=self.remove_read_only)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 13] Permission denied: '/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-in Support/Data/com.plexapp.system/DataItems/Deactivated/com.plexapp.agents.subzero/Sub-Zero.bundle/Sub-Zero.bundle/Contents/Libraries/Sub-Zero.bundle'

**Comment by pannal** [comment]
OK, that's even more interesting.

What did you try to uninstall there? The official channel version? Or did you try uninstalling a manually added Sub-Zero?

**Comment by pannal** [comment]
Can you list the permissions of `Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.subzero` and `Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.subzero\DataItems`?

**Comment by valkhyr1** [comment]
I try to uninstall the official channel version, but this didn't work. After deleting the Sub-Zero.bundle directory I installed both versions.

**Comment by valkhyr1** [comment]
1|darcy:/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.subzero #
ls -ltRa
.:
total 40
-rw-------  1 u0_a62 u0_a62  114 2017-07-19 19:25 HTTPCookies
drwx------  3 u0_a62 u0_a62 4096 2017-07-19 17:53 .
drwx------ 17 u0_a62 u0_a62 4096 2017-07-19 17:53 ..
drwx------  2 u0_a62 u0_a62 4096 2017-07-19 17:53 DataItems
-rw-------  1 u0_a62 u0_a62   55 2017-07-19 17:53 StoredValues

./DataItems:
total 16
drwx------ 2 u0_a62 u0_a62 4096 2017-07-19 17:53 .
drwx------ 3 u0_a62 u0_a62 4096 2017-07-19 17:53 ..

**Comment by pannal** [comment]
And the permissions of the folder `/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-in Support/Data/com.plexapp.system/DataItems/Deactivated/` and the underlying Sub-Zero ones?

Preparing test build.

**Comment by pannal** [comment]
There you go: https://github.com/pannal/Sub-Zero.bundle/archive/nvidia_shield_perms.zip

Please install it as Sub-Zero.bundle after deleting the old installation. It may show some more stuff in the logs about what's happening.

**Comment by pannal** [comment]
Does the uninstallation error only happen with Sub-Zero or with other plugins as well?

**Comment by valkhyr1** [comment]
Permissions of the folder /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-in Support/Data/com.plexapp.system/DataItems/Deactivated/
[output1.txt](https://github.com/pannal/Sub-Zero.bundle/files/1162854/output1.txt)

**Comment by valkhyr1** [comment]
[com.plexapp.agents.subzero.txt](https://github.com/pannal/Sub-Zero.bundle/files/1162866/com.plexapp.agents.subzero.txt)

**Comment by valkhyr1** [comment]
The uninstallation error was my own error, I was trying to remove sub-zero in the wrong order.

**Comment by pannal** [comment]
Got it. I found the error. Updating.

**Comment by valkhyr1** [comment]
Great!

**Comment by pannal** [comment]
Please try this beta build: https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.0.zip

**Comment by pannal** [comment]
If that doesn't fix it, I'll update the other debug build again.

**Comment by valkhyr1** [comment]
I have a working Sub-Zero 2 version on my Nvidia Shield :-)

**Comment by pannal** [comment]
Whoohooo! Thank you so much for bearing with me and debugging this!

**Comment by SteveVerniers** [comment]
Hi @pannal, what would this mean for people without Nvidia shield developer access or rooted access ? Does this mean we need to wait for Sub-Zero 2.x update or is this something we can only ever make work when shield tv is rooted ?

Kind regards
Steve

**Comment by pannal** [comment]
The fix is for everyone. You just have to wait for the next release to hit the official channel repository.

To install it before that happens you'll need root.

**Comment by SteveVerniers** [comment]
@pannal: thank you for you quick and clear reply.  I can wait until the next official channel update then ;)
Any rough ETA on that update ?
Thanks a lot for all your efforts !
Appreciated
Steve

**Comment by valkhyr1** [comment]
Sub-Zero 2.0.25.1635 is available now.

**Comment by SteveVerniers** [comment]
Super thanks ;) Seems to be working nicely ;)
Appreciated !!!

**Comment by SteveVerniers** [comment]
@pannal : After testing it today I get alot of "This channel is not responding." messages when using the channel (to force subtitle downloads, or just browse stuff like history and such)
This is behavior on the Nvidia Shield PMS.

`2017-07-30 11:09:27,359 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 11:09:30,119 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 11:09:32,472 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 11:09:34,579 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 11:15:21,018 (203fb3c450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/5/4e6f576711b1f41a868c10e863b986fde03034c.bundle/Contents/com.plexapp.agents.subzero
2017-07-30 11:15:31,124 (2044379450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/f/a11a55b10bfc9bd9b6f78a4d5879bdbba444afc.bundle/Contents/com.plexapp.agents.subzero
2017-07-30 11:15:46,042 (204427c450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/2/b10e2a54f418ec68bde8749aa66cae8a902e5fa.bundle/Contents/com.plexapp.agents.subzero
2017-07-30 12:02:52,019 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:02:55,142 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:02:59,687 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:03:01,864 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:03:12,910 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:03:32,761 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:04:15,318 (203fb3c450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/b/b9e76328442557d15138f9af4b3aff579e0f82e.bundle/Contents/com.plexapp.agents.subzero
2017-07-30 12:10:54,388 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:10:56,172 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:10:58,178 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:00,084 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:02,790 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:11,223 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:40,286 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:43,462 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:45,504 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:48,138 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:49,892 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:11:52,696 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:12:03,696 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:13:37,821 (2044379450) :  ERROR (logger:38) - subliminal_patch.core: Provider 'addic7ed' timed out
2017-07-30 12:39:11,460 (2044379450) :  CRITICAL (runtime:1128) - Exception in thread named '_handle_request' (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1126, in _start_thread
    f(*args, **kwargs)
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/interfaces/socketinterface.py", line 126, in _handle_request
    self.finish()
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/web.py", line 565, in finish
    self.request.finish()
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 432, in finish
    self.connection.finish()
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 262, in finish
    self._finish_request()
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 283, in _finish_request
    self.stream.close()
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Plug-ins-8fa494d15/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/iostream.py", line 124, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

2017-07-30 12:39:21,658 (203fb3c450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x20396c65f0>
2017-07-30 12:41:34,523 (203fb3c450) :  DEBUG (menu:187) - Stop logging to console`

For testing I also quickly setup a PMS on my synology NAS, since there is no restricted storage like the shield has, so I can provide you with results from both setups.

When I try and force subtitles on my NAS using the sub-zero channel he will correctly download both english and foreign languages I have selected.  This said he will sometimes not download foreign subtitles.  When I then go to the addicted site (with logged on credentials) and manually search for the foreign language it is there and I am able to download it.  This is mostl likely a seperated issue from this one (Should I make another post about this ?) or could this be a score issue ?  How can I find better information in the log files related to this ?

**Comment by pannal** [comment]
You should create a separate ticket for this, as it's unrelated. Please *attach* your full SZ log zip (see the wiki) to that ticket.
