### ISSUE TITLE
new PMS library items not showing in 'Items with missing subtitles' and/or existing items not updated properly

### ISSUE THREAD

**Issue by mickeldaelmans** [pannal/Sub-Zero.bundle#335]
**Case 1:** 
Newly added library items are not showing in 'Items with missing subtitles', unless triggered by manual refresh or plugin restart.  

Example:

Movie: Life During Wartime
Item visible in 'Items with missing subtitles': No
Added in PMS: 2017-08-18 08:39:09
SZ download history: "Life During Wartime (auto): English in Movies (podnapisi, score: 102), 2017-08-18 10:06:10"
SZ Log: 
com.plexapp.agents.subzero.log.2: 2017-08-18 10:06:09,047 (7ff1f43ff700) :  DEBUG (logger:28) - subliminal_patch.core: Saving <PodnapisiSubtitle 'http://www.podnapisi.net/subtitles/en-life-during-wartime-2009/W9Q3' [en:utf-8]> to u'/volume1/Media/Movies/Life During Wartime (2009)/Life During Wartime (2009) [BluRay, 1080p, x264, AAC, YTS.AG].en.srt'

Observation:
1. Dutch sub still missing, but movie doesnt show up in 'Items with missing subtitles'.
2. After manually refreshing 'Items with missing subtitles', movie does show up with correctly mentioning that the dutch sub is still missing. 

**Case 2:** 
Items that do show in 'Items with missing subtitles' do not get updated/refreshed properly even after SZ downloaded subs as part of a scheduled task or after manual metadata refresh in PMS

Example: 
Movie: 'The Exception'
Item visible in 'Items with missing subtitles': Yes, but mentions that it does not have any subs

SZ log shows external subs were found: 
(com.plexapp.agents.subzero.log.1: 2017-08-18 12:21:09,416 (7ff1f46ed700) :  DEBUG (logger:28) - subliminal_patch.core: external subs: found {u'The Exception (2017) [BluRay, 1080p, x264, AAC, YTS.AG].en.srt': <Language [en]>})

Observation: 
1. english srt subs are present 
2. manual refresh of 'Items with missing subtitles' does not update this.
 

Extra info:
SZ 2.0.25.1635 DEV
PMS 1.8.1.4139 
Synology DSM 6.1.3-15152 Update 1

[Logs_170818_14-11-43.zip](https://github.com/pannal/Sub-Zero.bundle/files/1234400/Logs_170818_14-11-43.zip)

**Comment by pannal** [comment]
What do you mean by "manual refreshing items with missing subtitles" exactly? You mean pressing "Get items with missing subtitles"?

**Comment by mickeldaelmans** [comment]
correct, 'Get items with missing subtitles'

**Comment by pannal** [comment]
Ah. I think there's a communication issue there. The output you see inside that menu always is the last (cached), it doesn't update automatically. For it to update you have to trigger the search again.

I can change that if that makes more sense, so it always searches/updates the list when the menu is entered.

**Comment by mickeldaelmans** [comment]
Ah, haha yeah that explains a lot :) Not sure if updating the list is necesary every time you enter it (I can imagine users clicking back and forth). Maybe have it update whenever the 'SearchAllRecentlyAddedMissing' task runs?

Just another suggestion: Have the menu-description show when and who updated the list:
"Last refresh by scheduler on [date/timestamp]"
"Last refresh by user on [date/timestamp]"

**Comment by pannal** [comment]
The list inside that menu doesn't get updated by the scheduler; the scheduled task fetches the missing items itself when it runs, only for that run. They don't affect each other. I'll look into it, though.

Apart from that: the other issue still persists?

**Comment by mickeldaelmans** [comment]
I guess the 'quickest' win would be to just add 'needs to be refreshed manually' to the menu description to make it clear that it doesnt get updated automatically. 

For Case 2: Issue seems to persist, SZ keeps mentioning 'no subtitles in storage', even while the logs show that it found an english sub and is still missing dutch.

Things I've tried:

-I just ran 'SearchAllRecentlyAddedMissing', no change in item status
-I tried refreshing the item individually through the menu:  Items with missing subtitles > The Exception > Refresh: The Exception; again no change
-  Clicked 'Get items with missing subtitles', no change

But when I check the log:
2017-08-18 16:04:12,759 (7ff1f46ed700) :  INFO (missing_subtitles:47) - Subs still missing for 'The Exception' (35164: 171564): set([<Language [nl]>])  

So that seems correct, looks like the list isnt getting updated properly.

[Logs_170818_16-05-30.zip](https://github.com/pannal/Sub-Zero.bundle/files/1234638/Logs_170818_16-05-30.zip)

**Comment by pannal** [comment]
I can see in your logs that SZ tries finding subtitles in dutch for The Exception, but the scores of the results are too low, so it doesn't download anything and it is correct in doing so: https://www.opensubtitles.org/en/subtitles/7070399/the-exception-nl

**Comment by pannal** [comment]
As for 'needs to be refreshed manually' - I think it may do the opposite. People would be even more inclined to trigger that menu manually, as they think that's needed to find subtitles.

**Comment by mickeldaelmans** [comment]
I have no issue with it not downloading dutch at the moment; issue is that it does have english subs available (on disk, downloaded by SZ) and this isnt reflected in the item.

**Comment by pannal** [comment]
And you are a 100% certain that that english subtitle came from SZ? Because SZ finds locally available subtitles and skips them if it's configured that way - the only time you can see subtitles when inspecting an item, is, when SZ itself has downloaded that subtitle, and knows stuff about it (from its subtitle storage).

**Comment by mickeldaelmans** [comment]
Yup, it was downloaded by SZ (see Logs_170818_14-11-43.zip above)

2017-08-18 05:58:12,809 (7ff1f43ff700) :  DEBUG (logger:28) - subliminal_patch.core: Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7056911/sid-Egy,3FDBfJrZScJmJ9WscB355rc/the-exception-en' [en:utf-8]> to u'/volume1/Media/Movies/The Exception (2017)/The Exception (2017) [BluRay, 1080p, x264, AAC, YTS.AG].en.srt'

**Comment by pannal** [comment]
Oh I see:
```
SearchAllRecentlyAddedMissing: Something went wrong when downloading specific subtitle: Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 448, in run
    time.sleep(PROVIDER_SLACK)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 147, in save_subtitles
    save_subtitles_to_file(downloaded_subtitles)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 99, in save_subtitles_to_file
    debug_mods=config.debug_mods, formats=config.subtitle_formats)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 619, in save_subtitles
    content = subtitle.get_modified_content(format=format)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/subtitle.py", line 299, in get_modified_content
    return fix_text(self.pysubs2_to_unicode(submods.f, format=format), **ftfy_defaults).encode(encoding="utf-8")
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/__init__.py", line 183, in fix_text
    normalization=normalization
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/__init__.py", line 277, in fix_text_segment
    text = fixes.fix_latin_ligatures(text)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/ftfy/fixes.py", line 381, in fix_latin_ligatures
    return text.translate(LIGATURES)
TypeError: character mapping must return integer, None or unicode
```

**Comment by pannal** [comment]
It actually fails to save the subtitle to the storage because of an issue with ftfy.

**Comment by pannal** [comment]
Yep, reported a bug: https://github.com/LuminosoInsight/python-ftfy/issues/81

I can fix that for the next version.

**Comment by mickeldaelmans** [comment]
Ah, glad I was not going crazy then :) Have been 'debugging' a bunch of issues at the same time and have been changing permissions, restarting PMS & SZ and adding and removing stuff trying to reproduce bugs, hehe.

I think I also see this error for this particular sub (see Logs_170818_14-11-43.zip above). Maybe the issues are related?
```
2017-08-18 05:58:12,808 (7ff1f43ff700) :  DEBUG (logger:28) - subliminal_patch.core: Subtitle formats requested: ['srt']
2017-08-18 05:58:12,809 (7ff1f43ff700) :  DEBUG (logger:28) - subliminal_patch.core: Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/7056911/sid-Egy,3FDBfJrZScJmJ9WscB355rc/the-exception-en' [en:utf-8]> to u'/volume1/Media/Movies/The Exception (2017)/The Exception (2017) [BluRay, 1080p, x264, AAC, YTS.AG].en.srt'
2017-08-18 05:58:12,810 (7ff1f43ff700) :  DEBUG (logger:28) - subliminal_patch.subtitle: Encoding already guessed: utf-8
2017-08-18 05:58:14,423 (7ff1f43ff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/35164'
2017-08-18 05:58:24,526 (7ff1f43ff700) :  ERROR (tasks:448) - SearchAllRecentlyAddedMissing: Something went wrong when downloading specific subtitle: Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 448, in run
    time.sleep(PROVIDER_SLACK)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 167, in save_subtitles
    store_subtitle_info(scanned_video_part_map, downloaded_subtitles, storage, mode=mode)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 30, in store_subtitle_info
    plex_item = get_item(video_id)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/items.py", line 28, in get_item
    item_container = Plex["library"].metadata(item_id)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/library/__init__.py", line 9, in metadata
    response = self.http.get('metadata', rating_key)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 95, in get
    return self.request('GET', path, params, query, data, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 87, in request
    response = request.request.send()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/lib.py", line 33, in send
    timeout=DEFAULT_TIMEOUT)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
    method=method,
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-c789b3fbb/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

```

**Comment by pannal** [comment]
Hm no, that's your PMS timing out while SZ tried to get metadata info about a certain item.

I don't know why or when that happens, that's been there for ages.

You can try and modify `subzero/constants.py:17` and set DEFAULT_TIMEOUT to something higher than 10 seconds.

**Comment by mickeldaelmans** [comment]
alright, might play around with that :) 

Back to Case 1: Maybe just mention in the menu when the list was last refreshed/updated? That would sort of indicate that it's not a list that gets updated automatically

**Comment by pannal** [comment]
Yeah I think that might work.

**Comment by mickeldaelmans** [comment]
I would argue that that wouldnt imply that the list is in a static state (until it gets refreshed)

**Comment by pannal** [comment]
Just trying to get around that added work to add another last-refresh-datapoint :D

But yeah, you're probably right. I'll ditch most of the current info of the description, though, I think. Who really reads that.

**Comment by mickeldaelmans** [comment]
Just thinking out loud.. Maybe Change 'Get items with missing subtitles' to
'Refresh items', and add something like "Click on 'refresh recent items' to
refresh results" in the main menu description?

Op 18 aug. 2017 18:15 schreef "pannal" <notifications@github.com>:

Just trying to get around that added work to add another
last-refresh-datapoint :D

But yeah, you're probably right. I'll ditch most of the current info of the
description, though, I think. Who really reads that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pannal/Sub-Zero.bundle/issues/335#issuecomment-323396791>,
or mute the thread

**Comment by pannal** [comment]
Hm no. It doesn't refresh any items, that'll confuse people with actually refreshing items.

**Comment by pannal** [comment]
I'd change it to: `Show items with missing subtitles` and description `Lists items with missing subtitles. Refreshed manually. Last refresh: X`.

**Comment by mickeldaelmans** [comment]
Sounds good :) or the lazy (huhu) way, you could remove mentioning the data
point of last refresh and say 'refreshed manually with 'Find items with
missing subs' or something like that :)

Op 18 aug. 2017 19:02 schreef "pannal" <notifications@github.com>:

I'd change it to: Show items with missing subtitles and description Lists
items with missing subtitles. Refreshed manually. Last refresh: X.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pannal/Sub-Zero.bundle/issues/335#issuecomment-323407776>,
or mute the thread

**Comment by pannal** [comment]
Hum, no? With 'Find items with missing subs' you mean "Search for missing subtitles ..."? Those two don't correlate and that information would be wrong.

**Comment by mickeldaelmans** [comment]
No no, I mean something else. On mobile now, but will elaborate with a
mockup when I get home in a bit.

Op 18 aug. 2017 19:25 schreef "pannal" <notifications@github.com>:

**Comment by mickeldaelmans** [comment]
Something like this. Having the datapoint/timestamp with the last refresh would be the icing on the cake, but something like this would make it more clear that user interaction is required to update the list. 

![mockup1](https://user-images.githubusercontent.com/27225485/29479874-fc29b830-8474-11e7-961e-a8d0cb3b09b5.jpg)
![mockup2](https://user-images.githubusercontent.com/27225485/29479875-fdfdf98c-8474-11e7-92b7-3c4d88b6a57a.jpg)

**Comment by pannal** [comment]
That looks smart. Keeping that :)

**Comment by pannal** [comment]
Implemented in current develop. Do you think adding a timestamp is worth it?

**Comment by mickeldaelmans** [comment]
I think the new description makes clear that it needs manual interaction to be updated; sounds clear to me, to be honest. Verb-usage should be good enough: clicking on "Show items" will "list" you these items. And it tells you to "find" items to "update list".

But, on a tangent: Maybe showing a timestamp in the 'Refresh' main menu item? It would inform the user what the last activity was for SZ. 
![mockup3](https://user-images.githubusercontent.com/27225485/29480415-776e519c-8478-11e7-81c1-82a1d8f0a91a.jpg)

Also, didnt saw your edit regarding:
"Edit 2 (many edits today): I can add an option for the timeout in the next version."

Sounds like a good option to include, but I wouldnt limit it to, lets say, 20s. If a service isnt responding in time there is probably something wrong; no need to stretch out those timeouts . Also, I'm not all to familiar with the PMS framework and I don't know if there might be performance penalties during scans/refreshes, but if thats the case I would add a little disclaimer mentioning that.

**Comment by pannal** [comment]
Yeah I'd only add that option as an enthusiast thing - there are PMS instances that respond very slowly out there.

As for the refresh item: That one currently is generic throughout the board. Changing that would mean a great deal of work. Not gonna happen soon with the changes I have in mind for 2.1+ :)

**Comment by pannal** [comment]
BTW, with the level of involvement you've gotten into regarding SZ, you might want to consider joining the [Slack](https://szslack.fragstore.net) and join the pros :)

**Comment by mickeldaelmans** [comment]
ah yes, I believe I have a slack account somewhere. Will check that out this weekend :)
