### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by goku-son** [pannal/Sub-Zero.bundle#369]
I was investigating an issue with Spanish subtitles not being downloaded and noted the following errors which may or may not be related but was asked to open an issue here. I am running the latest SZ and PMS.  Here are the errors being logged:

```
2017-10-21 10:02:21,645 (550) : ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 118, in list_subtitles_provider
ret = self[provider].list_subtitles(video, provider_languages)
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 69, in getitem
provider.initialize()
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 97, in initialize
lambda: checked(
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 36, in retry
return f()
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 98, in
self.server.LogIn(self.username, self.password, 'eng', os.environ.get("SZ_USER_AGENT", "Sub-Zero/2"))
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in call
return self.send(self.__name, args)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1602, in __request
verbose=self.__verbose
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1283, in request
return self.single_request(host, handler, request_body, verbose)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1311, in single_request
self.send_content(h, request_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1459, in send_content
connection.endheaders(request_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1053, in endheaders
self._send_output(message_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 897, in _send_output
self.send(msg)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 859, in send
self.connect()
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1278, in connect
server_hostname=server_hostname)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 353, in wrap_socket
_context=self)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 601, in __init
self.do_handshake()
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 830, in do_handshake
self._sslobj.do_handshake()SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

2017-10-21 14:51:08,565 (1444) : ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 118, in list_subtitles_provider
ret = self[provider].list_subtitles(video, provider_languages)
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 69, in getitem
provider.initialize()
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 97, in initialize
lambda: checked(
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 36, in retry
return f()
File "C:\Users\plex\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 98, in
self.server.LogIn(self.username, self.password, 'eng', os.environ.get("SZ_USER_AGENT", "Sub-Zero/2"))
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in call
return self.send(self.__name, args)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1602, in __request
verbose=self.__verbose
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1283, in request
return self.single_request(host, handler, request_body, verbose)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1311, in single_request
self.send_content(h, request_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1459, in send_content
connection.endheaders(request_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1053, in endheaders
self._send_output(message_body)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 897, in _send_output
self.send(msg)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 859, in send
self.connect()
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\httplib.py", line 1278, in connect
server_hostname=server_hostname)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 353, in wrap_socket
_context=self)
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 601, in __init
self.do_handshake()
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ssl.py", line 830, in do_handshake
self._sslobj.do_handshake()
```

**Comment by pannal** [comment]
@opensubtitles has the SSL certificate for your new server(s) changed and isn't trusted anymore?

**Comment by opensubtitles** [comment]
@pannal you can always test our api certificate here: https://www.ssllabs.com/ssltest/analyze.html?d=api.opensubtitles.org
There is not possible to get better mark than "A" I think.

**Comment by pannal** [comment]
@goku-son did this happen again recently? Can you check?

**Comment by vBm** [comment]
@opensubtitles A+ is the highest you can go :)
https://www.ssllabs.com/ssltest/analyze.html?d=mpc-hc.org
