### ISSUE TITLE
LockException: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by Isilorn** [pannal/Sub-Zero.bundle#417]
Hello,

After upgrading from master to the latest 2.1 beta I've got the following message when trying to find missing subtitles :
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1595300/com.plexapp.agents.subzero.log)

```
2017-12-31 17:28:30,672 (7feae3fff700) :  INFO (missing_subtitles:158) - Subs still missing for 'Supergirl S03E07, Wake Up' (32710: 85915): set([<Language [fr]>, <Language [en]>, <Language [ro]>])
2017-12-31 17:28:30,697 (7feae3fff700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/32709'
2017-12-31 17:28:30,734 (7feae3fff700) :  DEBUG (logger:28) - subzero.subtitle_storage: Loading subtitle storage data file: subs_32709.json.gz
2017-12-31 17:28:30,738 (7feae3fff700) :  ERROR (logger:34) - subzero.subtitle_storage: Couldn't load JSON data for subs_32709: Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/subtitle_storage.py", line 550, in load
    portalocker.lock(f, portalocker.LOCK_EX)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/portalocker/portalocker.py", line 78, in lock
    raise exceptions.LockException(exc_value)
LockException: [Errno 9] Bad file descriptor
``` #

**Comment by pannal** [comment]
That's an interesting find. In order to receive support for Beta 2.1, please join the SZ slack and follow everything else listed here: https://github.com/pannal/Sub-Zero.bundle/wiki/Beta-Notes

I'll invite you to the beta channel and we can debug this together. Those beta builds are not meant for people outside the beta program.

**Comment by pannal** [comment]
I see you've already done the most part, that's great. Beta 2.1 isn't handled via GitHub at the moment, so please join the Slack team.

**Comment by Isilorn** [comment]
Sorry for that I should have been more attentive to the beta notes :) just joined Slack
