### ISSUE TITLE
Subtitles won't download automatically but work fine manually

### ISSUE THREAD

**Issue by captainjack64** [pannal/Sub-Zero.bundle#430]
Hi,

I have an issue with subtitles not downloading automatically. The error in the logs seem a little ambiguous:

`2018-02-02 03:20:38,405 (2ebaa460) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 122, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 73, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 149, in initialize
    self.log_in()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 117, in log_in
    lambda: checked(
 [snip]
SSLError: ('The read operation timed out',)`

And:

`2018-02-02 18:21:16,002 (31aed460) :  ERROR (logger:38) - subliminal_patch.providers.tvsubtitles: Episode 9 not found
2018-02-02 18:21:50,752 (32d7c460) :  ERROR (tasks:456) - SearchAllRecentlyAddedMissing: Something went wrong when downloading specific subtitle: Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 456, in run
    time.sleep(PROVIDER_SLACK)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 171, in save_subtitles
    store_subtitle_info(scanned_video_part_map, downloaded_subtitles, storage, mode=mode)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/storage.py", line 30, in store_subtitle_info
    plex_item = get_item(video_id)
[snip]
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-4b377d295/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>`

However, if I force a refresh of an episode from Subzero channel manually, the subtitles download perfectly! Any ideas... using Diskstation Plex Server with the latest Subzero bundle...

**Comment by pannal** [comment]
Hm no, not sure. I'd need the full log zip when that happens. The timeout is an OpenSubtitles error I can't do anything about.

Please wait for the upcoming version 2.5 and see if that fixes your issue. If not, please follow the Wiki on how to obtain your log zip and drop it here.

**Comment by alexljames** [comment]
OK, thanks - very odd that it worked ok in the past and works manually. When is the new version out?

**Comment by pannal** [comment]
It's scheduled for this weekend.

**Comment by pannal** [comment]
Still an issue?

**Comment by alexljames** [comment]
Yes, still not downloading them automatically on Sub-Zero 2.5.0.2247

**Comment by pannal** [comment]
And still? You should have the newest version, 2.5.0.2287, by now.

**Comment by alexljames** [comment]
I'll need to check once some new programmes download but is there anything in those revisions that would affect automatic downloads? I will collect logs at the next opportunity and upload them here.

**Comment by alexljames** [comment]
No difference in behaviour, sadly. I am attaching the latest logs.

[Logs_180330_10-47-02.zip](https://github.com/pannal/Sub-Zero.bundle/files/1863296/Logs_180330_10-47-02.zip)
.

**Comment by pannal** [comment]
@alexljames those are OpenSubtitles timeouts. 

Please set your SZ log level to DEBUG (in SZ's settings), then refresh a video in question, wait a minute, then post your log zip again.
