### ISSUE TITLE
Issue with Nvidia shield and subzero channel 2.5.0.2247

### ISSUE THREAD

**Issue by ahiguero** [pannal/Sub-Zero.bundle#441]
Plex server installed on an nvidia shield and checking the logs the following issue occurs

android experience 6.3 has been installed on it and the systems was reset to factory defaults before installing plex and the sub zero channel please let me know if you need anything else

2018-02-19 11:06:40,887 (203027c450) :  ERROR (scheduler:132) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scheduler.py", line 130, in run_task
    task.run()
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 499, in run
    Thread.Sleep(PROVIDER_SLACK)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 113, in scan_videos
    skip_hashing=skip_hashing)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 84, in scan_video
    only_one=config.only_one)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/video.py", line 25, in set_existing_languages
    only_one=only_one).values())
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 591, in search_external_subtitles
    only_one=only_one))
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 519, in _search_external_subtitles
    for entry in scandir(dirpath):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/scandir.py", line 543, in scandir_python
    opendir_path = path.encode(file_system_encoding)
TypeError: encode() argument 1 must be string, not None
[Logs_180219_11-07-46.zip](https://github.com/pannal/Sub-Zero.bundle/files/1737683/Logs_180219_11-07-46.zip)

**Comment by ukdtom** [comment]
@pannal 

Shield do not set the lang in PMS :(

Saw it here:
https://github.com/ukdtom/WebTools.bundle/issues/489

**Comment by ahiguero** [comment]
thanks for the response. like i isad on this ticket though i did reset the shield to factory settings which would wipe it clean and just installed plex and the subzero channel form the plugin marketplace so no other "unauthorized apps"

let me know if you need more information form my side though

**Comment by pannal** [comment]
Hmm, I think I can add a workaround preventing that. Is your SHIELD rooted so you could test this?

**Comment by ahiguero** [comment]
Hello @pannal 

Thanks for your reply buddy. yes my shield is rooted but i lost my SuperSu when i did the reset to factory settings so i will root it again, so i can see the data directory. i am planning on doing that this thursday so let me know what i need to do to assist you..

**Comment by ahiguero** [comment]
device has been rooted, let me know what do you need me to test

**Comment by pannal** [comment]
@ahiguero please try this branch: https://github.com/pannal/Sub-Zero.bundle/archive/shield_test2.zip

Do you know how to manually install?

**Comment by ahiguero** [comment]
i am assuming the the manual isntlal would be like this:

- stop the plex server
- rename existing sub-zero bundle
- copy new subzero bundle (provided by you) to the corresponding folder
- start plex server

**Comment by pannal** [comment]
Nope, nothing else. Just be sure the new folder is named `Sub-Zero.bundle` and it has the same structure as the old one.

**Comment by ahiguero** [comment]
awesome... then i will test as soon as i get home from work and give you the results.

**Comment by ukdtom** [comment]
Actually, with rename, you must rename the extension (.bundle), since otherwise, it'll still be read

/T

**Comment by pannal** [comment]
Right. Just name it Sub-Zero.bundle.old, or delete it - your config data and storage stuff is stored elsewhere.

**Comment by pannal** [comment]
@ahiguero any news? :)

**Comment by ahiguero** [comment]
@pannal trying but no luck

i keep getting the following error on the plex server logs

eb 23, 2018 18:26:01.591 [23387] ERROR - Couldn't check for the existence of file "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Info.plist": boost::filesystem::status: Permission denied: "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Info.plist"
Feb 23, 2018 18:26:01.591 [23387] WARN - Couldn't determine bundle identifier for plug-in at: "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle"

folder does have the same permissions as the old one. at first when i copied it hte folder belonge dot the root user but still it was not working then i went and compared it with the previous one that i renamed and made sure that the new folder had the same permissions, rebooted and still shows this error and no channel appears. if i remove your package and rename the old folder the channel shows again.

**Comment by pannal** [comment]
Well, the folder has the same permissions, but did you do the permission change recursively?

`chown -R` or `chmod -R`? It can't access _files_ inside that folder.

**Comment by pannal** [comment]
@ahiguero want to join the [SZ slack](https://szslack.fragstore.net) for testing?

**Comment by ahiguero** [comment]
@pannal yes both chown an chmod were run with the -R command

**Comment by pannal** [comment]
@ahiguero any news? You didn't answer in Slack.

**Comment by jbreuer95** [comment]
Latest versions seems to work on my shield :)
I do get the following errors/warnings
```
2018-03-02 19:48:49,857 (202afb6450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x202acdeb18>
2018-03-02 19:48:55,798 (202afb6450) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x202acdeb18>
2018-03-02 19:49:00,516 (202afb6450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/c/1ce4bf1b8f7a2205823d48d6a99fa883dd46cf0.bundle/Contents/com.plexapp.agents.subzero
2018-03-02 19:51:10,473 (202e133450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/5/e3f04e70b6f718cfbe2ec17b3d95faac931d31f.bundle/Contents/com.plexapp.agents.subzero
2018-03-02 19:53:16,591 (202e133450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/c/cb131752fde70d55a9619b962d448c892cca149.bundle/Contents/com.plexapp.agents.subzero
2018-03-02 19:55:18,342 (202afb6450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/a/2556680ecf43527d62944e60bbac2b6dc2bdeca.bundle/Contents/com.plexapp.agents.subzero
2018-03-02 19:57:22,746 (202afb6450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/0/84d1d0fe0a039759ce4b5332e75e068524c7e79.bundle/Contents/com.plexapp.agents.subzero
2018-03-02 19:59:28,297 (202afb6450) :  ERROR (model:205) - Cannot read model from /data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Metadata/TV Shows/8/d78664eca172852ae6f3e0917fd51d175badef0.bundle/Contents/com.plexapp.agents.subzero
```

**Comment by pannal** [comment]
@jbreuer95 those are OK. The callback path is only a warning and not an issue, the errors are PMS-errors that don't affect SZ.

**Comment by jbreuer95** [comment]
Cool, only when i try to select an active subtitle i get this error now
```
2018-03-02 20:35:53,424 (202afb6450) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-f54242b6b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/item_details.py", line 255, in ListStoredSubsForItemMenu
    key=lambda x: x[1].date_added, reverse=True):
  File "/data/user/0/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/item_details.py", line 255, in <lambda.17>
    key=lambda x: x[1].date_added, reverse=True):
AttributeError: 'dict' object has no attribute 'date_added'
```
I am using a custom subtitle location btw

**Comment by pannal** [comment]
Can you attach the subtitle storage for that particular item? Get the media ID via `Plex Web -> three dots -> Get Info -> View XML`, then looking at the URL.

The file in question can be found in `Plug-in\ Support/Data/com.plexapp.agents.subzero/DataItems/MEDIA_ID.json.gz`.

**Comment by jbreuer95** [comment]
[subs_385.json.gz](https://github.com/pannal/Sub-Zero.bundle/files/1776475/subs_385.json.gz)

**Comment by pannal** [comment]
Did you add something to your blacklist for that item?

**Comment by jbreuer95** [comment]
Yes i did seem to have done that, i was trying to download a new episode om my android tv and must have clicked blacklist somewhere

**Comment by jbreuer95** [comment]
I get the same error after removing it from the blacklist

**Comment by pannal** [comment]
That's OK. Do you have the means to install a development version of SZ? You just discovered a bug :)

**Comment by jbreuer95** [comment]
I already have a dev version running :), you cant get the latest version in the official channel store yet

**Comment by pannal** [comment]
Nice, please try the current develop version: https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.1.zip

**Comment by jbreuer95** [comment]
sure, might take some time, installing a custom version on the shield is not as straight forward as a regular server. max half an hour-

**Comment by pannal** [comment]
Thanks. Let's track this separate issue in #450

**Comment by ahiguero** [comment]
the latest dev build Sub-Zero 2.5.0.2287 DEV sees to have fixed the issue withe schedule tasks

**Comment by pannal** [comment]
Great, closing. Thank you for testing!
