### ISSUE TITLE
Subtitles won't download - opensubtitles times out.

### ISSUE THREAD

**Issue by yakadoodle** [pannal/Sub-Zero.bundle#451]
Hi, I am having trouble to get any subtitles downloaded using Sub-Zero.
I am using the latest version on the Plex channel.
Have tried the automatic search and the force find subtitles option.
See errors in log below / attached.
I have been trying this for about a week. I can reach the opensubtitle website.
The subtitles for the show i want do exist on the opensubtitle website. I have also tried a couple of different shows.

Any ideas?
Thanks! :)

[com.plexapp.agents.subzero.zip](https://github.com/pannal/Sub-Zero.bundle/files/1776591/com.plexapp.agents.subzero.zip)

2018-03-02 20:55:56,447 (7fefc3fff700) :  ERROR (logger:38) - subliminal_patch.core: Failed to refine video: Traceback (most recent call last):
2018-03-02 20:56:46,540 (7fefc27fc700) :  ERROR (logger:38) - subliminal_patch.core: Provider 'opensubtitles' timed out
2018-03-02 21:03:44,329 (7fefc27fc700) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function IgnoreMenu at 0x7fefd14ecf50>
2018-03-02 21:03:44,888 (7fefc27fc700) :  ERROR (logger:38) - subliminal_patch.core: Failed to refine video: Traceback (most recent call last):
2018-03-02 21:04:34,982 (7fefd2ffd700) :  ERROR (logger:38) - subliminal_patch.core: Provider 'opensubtitles' timed out

**Comment by phatassdk** [comment]
Have the same issue on Shield using SZ .2287. See attached logs with a refresh of a TV show with verbose level DEBUG.
[Logs_180319_08-26-02.zip](https://github.com/pannal/Sub-Zero.bundle/files/1836394/Logs_180319_08-26-02.zip)

**Comment by pannal** [comment]
Well, the current timeout for opensubtitles API connections is 10 seconds. That's extremely long to wait for an API response.

I can't really help you with that, as it's an issue with the provider's server load or the connection inbetween.

Sadly @opensubtitles hasn't been answering me lately.

**Comment by opensubtitles** [comment]
Hi, we are aware of the timeouts and stuff, we are monitoring our API closely. We are working on some workaround, which hopefully will again make our service fast enough. The problem is with scaling, the new user agent Terrarium TV started using our service, and it makes 50% of all requests...So even blocking it takes some needed resources...we are here. @pannal contact me directly

**Comment by pannal** [comment]
@opensubtitles I'm available via XMPP, as always.

Did you change your API result format? I'm receiving a dictionary for `response["data"]` when querying `SearchSubtitles`. The API docs state that an array is returned.

**Comment by phatassdk** [comment]
It seems as if the issue is still present in the recent update.
See attached logs.

"DEBUG (logger:28) - subliminal_patch.providers.mixins: Retrying OpenSubtitlesProvider, try: 1/2, exception: Traceback (most recent call last)"

[Logs_180326_13-25-28.zip](https://github.com/pannal/Sub-Zero.bundle/files/1847595/Logs_180326_13-25-28.zip)

**Comment by Haxy89** [comment]
Issue is still present:


2018-03-26 14:38:45,023 - com.plexapp.agents.subzero       (7f82a8ff9700) :  DEBUG (logger:28) - subliminal_patch.providers.mixins: Retrying OpenSubtitlesProvider, try: 1/2, exception: Traceback (most recent call last):


  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/mixins.py", line 44, in retry


    return f()


  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 230, in <lambda>


    lambda: self.retry(lambda: checked(self.server.SearchSubtitles(self.token, criteria)))


  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1243, in __call__


    return self.__send(self.__name, args)


  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1602, in __request


    verbose=self.__verbose


  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1283, in request


    return self.single_request(host, handler, request_body, verbose)


  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/xmlrpclib.py", line 1331, in single_request


    response.msg,


ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 520 Origin Error>
