### ISSUE TITLE
Unexpected error in provider 'opensubtitles'

### ISSUE THREAD

**Issue by nivong** [pannal/Sub-Zero.bundle#469]
Was checking the logs why some titles didnt get any sub updates and found this error inbetween the lines. Is this on my end? Looks like API change of opensubtitles.
```
2018-03-19 19:19:02,708 (-f2df4c0) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 157, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 154, in initialize
    self.log_in()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 113, in log_in
    lambda: checked(
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/mixins.py", line 44, in retry
    return f()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 115, in <lambda>
    os.environ.get("SZ_USER_AGENT", "Sub-Zero/2"))
  File "/volume1/@appstore/Plex Media Server/Resources/Python/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/volume1/@appstore/Plex Media Server/Resources/Python/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/volume1/@appstore/Plex Media Server/Resources/Python/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/volume1/@appstore/Plex Media Server/Resources/Python/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 520 Origin Error>
```

**Comment by nivong** [comment]
And also seeing this error:
```
2018-03-19 19:30:29,976 (-ea954c0) :  ERROR (logger:38) - subliminal_patch.providers.tvsubtitles: Episode 2 not found
2018-03-19 19:30:35,629 (-f0714c0) :  WARNING (logger:38) - subliminal.providers.addic7ed: Series not found in show ids
2018-03-19 19:30:36,478 (-f0714c0) :  WARNING (logger:38) - subliminal.providers.addic7ed: Series not found in show ids
2018-03-19 19:31:25,724 (-fa004c0) :  CRITICAL (runtime:1128) - Exception in thread named '_handle_request' (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1126, in _start_thread
    f(*args, **kwargs)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/interfaces/socketinterface.py", line 126, in _handle_request
    self.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/web.py", line 565, in finish
    self.request.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 432, in finish
    self.connection.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 262, in finish
    self._finish_request()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 283, in _finish_request
    self.stream.close()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/iostream.py", line 124, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by pannal** [comment]
No that's an OpenSubtitles connection error. Nothing you or I can do about that, sorry!

**Comment by nivong** [comment]
thanks also found some other errors. WIll post new issue with debug log attached.
