### ISSUE TITLE
String error for opensubtitles

### ISSUE THREAD

**Issue by hogmac** [pannal/Sub-Zero.bundle#472]
Seems SZ can't search for subtitles at opensubtitles, I'm getting this error and had no idea what may be wrong. I'm able to download subtitles via their website, however via plex and SZ does not seems to work.  This is the error I got, can you look into and advise on my issue please:

2018-03-24 00:14:17,895 (7ff36754c700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 157, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 201, in list_subtitles
    use_tag_search=self.use_tag_search, only_foreign=self.only_foreign)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 243, in query
    language = Language.fromopensubtitles(subtitle_item['SubLanguageID'])
TypeError: string indices must be integers, not str

2018-03-24 00:14:17,899 (7ff36754c700) :  INFO (logger:38) - subliminal_patch.core: Discarding provider opensubtitles
2018-03-24 00:14:17,899 (7ff36754c700) :  INFO (logger:38) - subliminal_patch.core: Downloaded 0 subtitle(s)

**Comment by pannal** [comment]
Yeah, they seem to have changed their API output format without updating their API docs. https://github.com/pannal/Sub-Zero.bundle/issues/451#issuecomment-375660428

Fixed in develop-2.5, might release a hotfix tomorrow.

**Comment by hogmac** [comment]
> Fixed in develop-2.5, might release a hotfix tomorrow.

Ok it will be nice as this is not working on any way so far.  Thanks and will appreciate if you can reply when have a hotfix to try it out.

**Comment by pannal** [comment]
Release is out. You'll be auto updated (in the next day or so?) if you installed SZ via the official plugin repository.
