### ISSUE TITLE
 Something went wrong when running SearchAllRecentlyAddedMissing:

### ISSUE THREAD

**Issue by halali** [pannal/Sub-Zero.bundle#498]
Hi,

im getting this error 
```python
2018-04-17 11:35:17,551 (42e0) :  ERROR (logkit:22) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\support\scheduler.py", line 130, in run_task
    task.run()
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\support\tasks.py", line 505, in run
    Thread.Sleep(self.PROVIDER_SLACK)
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\support\items.py", line 33, in get_item
    item_container = Plex["library"].metadata(item_id)
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\plex\interfaces\library\__init__.py", line 9, in metadata
    response = self.http.get('metadata', rating_key)
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\plex\core\http.py", line 95, in get
    return self.request('GET', path, params, query, data, **kwargs)
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\plex\core\http.py", line 87, in request
    response = request.request.send()
  File "F:\Plex\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Code\support\lib.py", line 33, in send
    timeout=DEFAULT_TIMEOUT)
  File "F:\Plex\Plex Media Server\Resources\Plug-ins-215c28d86\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\networkkit.py", line 194, in Request
    method=method,
  File "F:\Plex\Plex Media Server\Resources\Plug-ins-215c28d86\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "F:\Plex\Plex Media Server\Resources\Plug-ins-215c28d86\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "F:\Plex\Plex Media Server\Resources\Plug-ins-215c28d86\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 141, in __init__
    self.load()
  File "F:\Plex\Plex Media Server\Resources\Plug-ins-215c28d86\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "F:\Plex\Plex Media Server\python27.zip\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "F:\Plex\Plex Media Server\python27.zip\urllib2.py", line 447, in _open
    '_open', req)
  File "F:\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "F:\Plex\Plex Media Server\python27.zip\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "F:\Plex\Plex Media Server\python27.zip\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "F:\Plex\Plex Media Server\python27.zip\httplib.py", line 1136, in getresponse
    response.begin()
  File "F:\Plex\Plex Media Server\python27.zip\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "F:\Plex\Plex Media Server\python27.zip\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "F:\Plex\Plex Media Server\python27.zip\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```
im using last version of SZ, and try last dev version but same error

[Logs_180417_13-18-35.zip](https://github.com/pannal/Sub-Zero.bundle/files/1919434/Logs_180417_13-18-35.zip)

**Comment by pannal** [comment]
That's a timeout when querying the Plex Server. Not really much I can do about that - I can catch that error and make the task not fail, though.

**Comment by pannal** [comment]
This doesn't happen all the time I guess?

**Comment by halali** [comment]
This happen all the time. Sometimes after 7min simetimes after 30min of scanning.

It scan 570 items for 2 languages

**Comment by halali** [comment]
But if will not fail all the time, i dont care about 1 item will not be scanned
