### ISSUE TITLE
Subzero crashing Plex server (server unresponsive, needs restart)

### ISSUE THREAD

**Issue by ranasats** [pannal/Sub-Zero.bundle#514]
Hi, 

I have a dockered plex server and am running SubZero (Sub-Zero 2.5.4.2527). Every few hours I get this error in my plex logs and I can not access plex anymore without a restart of the container.

`2018-05-10 06:27:34,359 - com.plexapp.agents.subzero       (14570ac75700) :  ERROR (scheduler:132) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scheduler.py", line 130, in run_task
    task.run()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 505, in run
    Thread.Sleep(self.PROVIDER_SLACK)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/items.py", line 35, in get_item
    item_container = Plex["library"].metadata(item_id)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/interfaces/library/__init__.py", line 9, in metadata
    response = self.http.get('metadata', rating_key)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 95, in get
    return self.request('GET', path, params, query, data, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/plex/core/http.py", line 87, in request
    response = request.request.send()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/lib.py", line 33, in send
    timeout=DEFAULT_TIMEOUT)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 194, in Request
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-31d3c0c65/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
`

Thanks.

**Comment by pannal** [comment]
Hmm, that doesn't indicate that SZ crashes your server - that simply says, that the server didn't answer in the right amount of time, via its API.

**Comment by ranasats** [comment]
Only reason I think that is that I've since disabled Subzero and plex no longer crashes. That entry is the last thing in my logs file before plex freezes up and stops writing. Not sure if there is another file I can look at to get better information for you?

**Comment by pannal** [comment]
Hmm, not sure. SZ does heavily use the PMS API, @ukdtom any ideas?

**Comment by ukdtom** [comment]
100% not a SZ issue IMHO

And with a snip from a log, it's not possible to say anything further.

Strongly suggest, that you post in the Plex Server forums, with logs in a zip

**Comment by pannal** [comment]
Yeah, you can zip up your Logs folder and attach it here. But I'd follow @ukdtom's advice as well and post on the forums.

**Comment by pannal** [comment]
Closing for now, please reopen if in question
