### ISSUE TITLE
Having issues with subtitles providers authentication

### ISSUE THREAD

**Issue by iHateThisGameSo** [pannal/Sub-Zero.bundle#525]
I am having issues with subtitles, and checking the logs I've seen some error messages with authentication to subtitle providers like bellow:

```
2018-05-29 14:25:40,653 (320) :  DEBUG (logkit:13) - Registering LoggerHandler for dependency: subzero
2018-05-29 14:26:19,967 (43c8) :  ERROR (logkit:22) - subliminal_patch.core: Cannot parse language code u'ENGLISH'
2018-05-29 14:26:29,200 (2718) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Login failed, please check your credentials
2018-05-29 14:26:30,977 (2718) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 225, in list_subtitles
    use_tag_search=self.use_tag_search, only_foreign=self.only_foreign)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 254, in query
    lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria)))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 144, in use_token_or_login
    self.log_in()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 131, in log_in
    lambda: checked(
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 45, in retry
    return f()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 132, in <lambda>
    lambda: self.server.LogIn(self.username, self.password, 'eng',
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 338, in checked
    raise Unauthorized
Unauthorized

2018-05-29 14:26:32,005 (3db8) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 99, in __getitem__
    provider.initialize()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 198, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: mylogin

2018-05-29 14:27:18,039 (43c8) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Logout failed: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in terminate
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 331, in checked
    response = fn()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in <lambda>
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled

2018-05-29 14:44:53,680 (35cc) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Login failed, please check your credentials
2018-05-29 14:44:54,108 (26d4) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 99, in __getitem__
    provider.initialize()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 198, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: mylogin

2018-05-29 14:44:54,388 (35cc) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 225, in list_subtitles
    use_tag_search=self.use_tag_search, only_foreign=self.only_foreign)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 254, in query
    lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria)))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 144, in use_token_or_login
    self.log_in()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 131, in log_in
    lambda: checked(
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 45, in retry
    return f()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 132, in <lambda>
    lambda: self.server.LogIn(self.username, self.password, 'eng',
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 338, in checked
    raise Unauthorized
Unauthorized

2018-05-29 14:44:55,525 (8b0) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Logout failed: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in terminate
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 331, in checked
    response = fn()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in <lambda>
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled

2018-05-29 14:48:13,499 (2bb0) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function inner at 0x087436F0>
2018-05-29 14:48:17,635 (4428) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function inner at 0x087436F0>
2018-05-29 14:48:33,994 (52a8) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function inner at 0x087436F0>
2018-05-29 14:48:42,766 (4c68) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function inner at 0x087436F0>
2018-05-29 14:48:52,165 (1044) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Login failed, please check your credentials
2018-05-29 14:48:52,523 (764) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'legendastv': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 99, in __getitem__
    provider.initialize()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal\providers\legendastv.py", line 198, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: mylogin

2018-05-29 14:48:52,887 (1044) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 225, in list_subtitles
    use_tag_search=self.use_tag_search, only_foreign=self.only_foreign)
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 254, in query
    lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria)))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 144, in use_token_or_login
    self.log_in()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 131, in log_in
    lambda: checked(
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\mixins.py", line 45, in retry
    return f()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 132, in <lambda>
    lambda: self.server.LogIn(self.username, self.password, 'eng',
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 338, in checked
    raise Unauthorized
Unauthorized

2018-05-29 14:48:54,460 (410) :  ERROR (logkit:22) - subliminal_patch.providers.opensubtitles: Logout failed: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in terminate
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 331, in checked
    response = fn()
  File "C:\Users\Username\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\opensubtitles.py", line 186, in <lambda>
    checked(lambda: self.server.LogOut(self.token))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
```

Nothing has been changed from when it used to work

**Comment by iHateThisGameSo** [comment]
No VIP checked

**Comment by pannal** [comment]
Are you using the newest official version? Or did you install manually?

**Comment by iHateThisGameSo** [comment]
Using Sub-Zero 2.5.4.2541, cannot really remember how it was installed.

**Comment by pannal** [comment]
Are you perhaps using a password manager and it accidentally changed the username/password settings based on your plex username/password?

**Comment by iHateThisGameSo** [comment]
I do use and I thought of that, I manually copied and pasted the user/pass infos again, still having issues

**Comment by pannal** [comment]
Weird. Digging a little further, not sure what's up here.

**Comment by iHateThisGameSo** [comment]
Sure thing, let me know if I can help or provide more info/logs, willing to collaborate :)

**Comment by iHateThisGameSo** [comment]
I just disabled some providers that I don't use (and don't recall enabling, maybe in the latest update?)

**Comment by iHateThisGameSo** [comment]
Hmmmm... it seems to be working fine now, I did a manual search for missing itens, could see no auth errors, only saw a traceback for the refiner(?) but sure enough it brought back some subs now. Can't say if it was the changes.

**Comment by pannal** [comment]
Can you get me your current log zip (see wiki) so I can take a look if anything weird's happening?

**Comment by iHateThisGameSo** [comment]
[Logs_180606_11-32-18.zip](https://github.com/pannal/Sub-Zero.bundle/files/2077208/Logs_180606_11-32-18.zip)
[Logs_180606_13-24-21.zip](https://github.com/pannal/Sub-Zero.bundle/files/2077209/Logs_180606_13-24-21.zip)
[Logs_180529_14-49-10.zip](https://github.com/pannal/Sub-Zero.bundle/files/2077210/Logs_180529_14-49-10.zip)

Full logs zip from the day when I openend the issue, earlier this morning and now

**Comment by pannal** [comment]
Looks fine, seems like TVDB didn't answer.

**Comment by pannal** [comment]
Wait, I've just noticed this:

```
raise AuthenticationError(self.username)
AuthenticationError: mylogin
```

Apparently "mylogin" was you username.

**Comment by pannal** [comment]
Closing

**Comment by iHateThisGameSo** [comment]
I had redacted my real username for "mylogin", you can see the right info on the logs.

**Comment by pannal** [comment]
OK. Please reopen if it happens again :)

**Comment by iHateThisGameSo** [comment]
Will do, thank you very much for the prompt support!
