### ISSUE TITLE
SubZero stopped downloading subs automatically and "Refresh" doesn't work anymore.

### ISSUE THREAD

**Issue by paolobasso99** [pannal/Sub-Zero.bundle#526]
Hi, the plugin stopped downloading subs automatically and "refresh" does not work anymore, if I download them through "List English subtitles" it works.

In the logs I saw this error:
```
2018-06-23 23:28:42,437 (2820) :  ERROR (logkit:22) - subliminal_patch.core: Failed to refine video: Traceback (most recent call last):
  File "C:\Users\basso\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 865, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "C:\Users\basso\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\refiners\tvdb.py", line 82, in refine
    original_match = series_re.match(result['seriesName']).groupdict()
TypeError: expected string or buffer

2018-06-23 23:28:42,444 (2820) :  ERROR (logkit:22) - subliminal_patch.core: Failed to refine video: Traceback (most recent call last):
  File "C:\Users\basso\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 865, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "C:\Users\basso\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\refiners\tvdb.py", line 82, in refine
    original_match = series_re.match(result['seriesName']).groupdict()
TypeError: expected string or buffer
```

Is there a way to fix it? I've already tried to uninstall Plex, deleting plugins and the reinstalling it but the problem persists.

**Comment by paolobasso99** [comment]
[Logs_180624_11-33-17.zip](https://github.com/pannal/Sub-Zero.bundle/files/2130645/Logs_180624_11-33-17.zip)

I didn't change my primary video library.

**Comment by paolobasso99** [comment]
Any chance to fix it?

**Comment by pannal** [comment]
Sorry, I can't do anything right now. I'll help you in the coming week.

**Comment by pannal** [comment]
Does this still happen? I can't really see anything inside your logs.

If it does, please set SZ's logging to DEBUG, refresh an item, then post your logs again.
