### ISSUE TITLE
NameError: global name 'Log' is not defined

### ISSUE THREAD

**Issue by zanglang** [pannal/Sub-Zero.bundle#569]
This exception pops up occasionally in the PMS logs. Looking at https://github.com/pannal/Sub-Zero.bundle/blob/bb2ed5a1167bb71936e573ec824f6701d667682d/Contents/Libraries/Shared/subliminal_patch/subtitle.py#L198 seems to me that Log.Debug should be written as logger.debug?

```2018-09-10 16:32:02,222 (7f91a9395700) :  ERROR (scheduler:132) - Scheduler: Something went wrong when running SearchAllRecentlyAddedMissing: Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scheduler.py", line 130, in run_task
    task.run()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 508, in run
    Thread.Sleep(self.PROVIDER_SLACK)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/download.py", line 119, in download_best_subtitles
    language_hook=language_hook)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 730, in download_best_subtitles
    compute_score=compute_score)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 403, in download_best_subtitles
    if self.download_subtitle(subtitle):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 308, in download_subtitle
    if not subtitle.is_valid():
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/subtitle.py", line 215, in is_valid
    text = self.text
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/subtitle.py", line 70, in text
    return self.content.decode(self.guess_encoding(), errors='replace')
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/subtitle.py", line 198, in guess_encoding
    Log.Debug("bs4 detected encoding: %s" % a.original_encoding)
NameError: global name 'Log' is not defined```

**Comment by pannal** [comment]
Absolutely right. My bad. Will be fixed in the next version.
