### ISSUE TITLE
ProviderError: More than one file to unzip

### ISSUE THREAD

**Issue by bwanshoom** [pannal/Sub-Zero.bundle#60]
Using v 1.2.11.180

Several of my movies are getting errors in the logs like the following:

    2015-10-28 08:23:04,656 (7fd45e7fc700) :  INFO (logger:31) - subliminal_patch.patch_providers.podnapisi: Downloading subtitle <PodnapisiSubtitle 'http://www.podnapisi.net/subtitles/en-cast-away-2000/MOUy' [en]>
    2015-10-28 08:23:04,779 (7fd45e7fc700) :  DEBUG (logger:21) - requests.packages.urllib3.connectionpool: "GET /subtitles/MOUy/download?container=zip HTTP/1.1" 302 160
    2015-10-28 08:23:04,915 (7fd45e7fc700) :  DEBUG (logger:21) - requests.packages.urllib3.connectionpool: "GET /subtitles/MOUy/download?container=zip HTTP/1.1" 200 21527
    2015-10-28 08:23:05,036 (7fd45e7fc700) :  ERROR (logger:27) - subliminal_patch.patch_provider_pool: Unexpected error in provider u'podnapisi', Traceback: Traceback (most recent call last):
      File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 212, in download_subtitle
        self[subtitle.provider_name].download_subtitle(subtitle)
      File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/podnapisi.py", line 20, in download_subtitle
        raise ProviderError('More than one file to unzip')
    ProviderError: More than one file to unzip

**Comment by pannal** [comment]
Yeah it has two subtitle files inside. I'll see what I can do.

**Comment by pannal** [comment]
Hmm, so the file it wanted to download the subs for, was it a 2 CD file?
Otherwise I'll have to add functionality to skip those subtitles instead of erroring out.

**Comment by pannal** [comment]
Can you provide the full log, or at least more context than above?

**Comment by bwanshoom** [comment]
I don't have write permissions in this repo to attach the log to this issue. Here's a link to what I think is the pertinent section of the session:  http://pastebin.com/m6iRyg0q

**Comment by pannal** [comment]
OK noted. It downloads the "best" subtitle, but it's 2 CD, which it can't handle. I'll add code to skip the subtitle in that case and try the next one, instead of letting the provider fail.
