### ISSUE TITLE
Sonarr/Radarr refiner failing with SSL error

### ISSUE THREAD

**Issue by chris3ware** [pannal/Sub-Zero.bundle#610]
Hi

I have enabled the Sonarr/Radarr refiners and I wondered if HTTPS API access was supported?

Sonarr/Radarr run on a different server.

I generate my own Certificates and I have imported the root cert into my Plex Servers certificate store. I can access the Sonarr API with the curl command successfully.

[chris@pms ~]$ curl https://SONARR_IP:SONARR_PORT/api/system/status?apikey=API_KEY
{
  "version": "2.0.0.5252",
  "buildTime": "2018-11-28T10:57:40.150019Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": false,
  "startupPath": "/opt/NzbDrone",
  "appData": "/config",
......

However, when I enable the refiners I get the following Traceback in the Subzero debug logs:

2019-01-15 09:14:39,725 (7fc536ffd700) :  DEBUG (sandbox:19) - Sonarr: NOT WORKING - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/interface/menu.py", line 291, in check_connections
    except HTTPError, e:
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/refiners/drone.py", line 83, in status
    return self.get("system/status", requests_kwargs=kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/refiners/drone.py", line 71, in get
    r = self.session.get(url, params=params, **(requests_kwargs or {}))
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 43, in request
    return super(CertifiSession, self).request(*args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='topsykretts.userlan.3ware.co.uk', port=9999): Max retries exceeded with url: /api/system/status (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

Thanks

**Comment by pannal** [comment]
Is this a self-signed certificate? If not: I've updated certifi to the newest version in the upcoming release. That might fix your issue.

**Comment by pannal** [comment]
Otherwise use `advanced_settings.json` (see `advanced_settings.json.template` for instructions) and set `"ssl_no_verify": true` for sonarr/radarr.
