### ISSUE TITLE
SubZero doesn't recognized any of my series

### ISSUE THREAD

**Issue by ThomasClemenceau** [pannal/Sub-Zero.bundle#632]
Hi, I have a problem, since yesterday, seems that SubZero can't recognized my series :

```
2019-04-12 13:00:56,990 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6181'
2019-04-12 13:00:58,701 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6162'
2019-04-12 13:01:00,117 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6024'
2019-04-12 13:01:00,393 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/4684'
2019-04-12 13:01:24,912 (7f6b25a95700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 111, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: AthAshino

2019-04-12 13:01:29,564 (7f6b256a7700) :  ERROR (logger:34) - subliminal.providers.tvsubtitles: No show id found for u'Better Call Saul' ({'year': 2015})
2019-04-12 13:01:33,782 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6181'
2019-04-12 13:01:34,291 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6162'
2019-04-12 13:01:37,679 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/6024'
2019-04-12 13:01:37,751 (7f6af6518700) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/library/metadata/4684'
2019-04-12 13:02:34,623 (7f6ae6b7d700) :  CRITICAL (runtime:1128) - Exception in thread named '_handle_request' (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1126, in _start_thread
    f(*args, **kwargs)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/interfaces/socketinterface.py", line 126, in _handle_request
    self.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/web.py", line 565, in finish
    self.request.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 432, in finish
    self.connection.finish()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 262, in finish
    self._finish_request()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/httpserver.py", line 283, in _finish_request
    self.stream.close()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado/iostream.py", line 124, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

2019-04-12 13:02:45,032 (7f6ae7a23700) :  CRITICAL (objects:73) - Exception setting attribute 'title2' of object <menu_helpers.SubFolderObjectContainer object at 0x7f6af6c9f050> to SÃ©ries TV: Better Call Saul S01E02 (type: <type 'str'>) (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 71, in _set_attribute
    el.set(convert_name(name), value)
  File "lxml.etree.pyx", line 699, in lxml.etree._Element.set (lxml-2.3/src/lxml/lxml.etree.c:34531)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (lxml-2.3/src/lxml/lxml.etree.c:15781)
  File "apihelpers.pxi", line 1366, in lxml.etree._utf8 (lxml-2.3/src/lxml/lxml.etree.c:22211)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

2019-04-12 13:02:54,023 (7f6af4d59700) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/TV Shows/a/047ef1fbf988ed23af02bc7e20c940bdcde0d7e.bundle/Contents/com.plexapp.agents.subzero
2019-04-12 13:02:56,598 (7f6af477d700) :  ERROR (logger:34) - subliminal.providers.tvsubtitles: No show id found for u'Better Call Saul' ({'year': 2015})
2019-04-12 13:02:56,781 (7f6af5960700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 111, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: AthAshino

2019-04-12 13:03:12,669 (7f6af5960700) :  ERROR (model:205) - Cannot read model from /volume1/Plex/Library/Application Support/Plex Media Server/Metadata/TV Shows/a/a8e863b74906c3438e1d84db6512443b982d18f.bundle/Contents/com.plexapp.agents.subzero
2019-04-12 13:03:21,208 (7f6af4a6b700) :  CRITICAL (objects:73) - Exception setting attribute 'title2' of object <menu_helpers.SubFolderObjectContainer object at 0x7f6af7046f90> to SÃ©ries TV: Better Call Saul S01E01 (type: <type 'str'>) (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 71, in _set_attribute
    el.set(convert_name(name), value)
  File "lxml.etree.pyx", line 699, in lxml.etree._Element.set (lxml-2.3/src/lxml/lxml.etree.c:34531)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (lxml-2.3/src/lxml/lxml.etree.c:15781)
  File "apihelpers.pxi", line 1366, in lxml.etree._utf8 (lxml-2.3/src/lxml/lxml.etree.c:22211)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

2019-04-12 13:03:40,381 (7f6af4a6b700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 111, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: AthAshino

2019-04-12 13:03:42,001 (7f6ae6b7d700) :  ERROR (logger:34) - subliminal.providers.tvsubtitles: No show id found for u'American Gods' ({'year': 2017})
2019-04-12 13:03:52,503 (7f6ae5cd7700) :  ERROR (logger:34) - subliminal.providers.tvsubtitles: No show id found for u'American Gods' ({'year': 2017})
2019-04-12 13:03:52,837 (7f6af477d700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 99, in __getitem__
    provider.initialize()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/addic7ed.py", line 111, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: AthAshino

2019-04-12 13:03:54,879 (7f6ae6b7d700) :  CRITICAL (objects:73) - Exception setting attribute 'title2' of object <menu_helpers.SubFolderObjectContainer object at 0x7f6af700ae10> to SÃ©ries TV: American Gods S01E07, A Prayer for Mad Sweeney (type: <type 'str'>) (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-ad6e39743/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 71, in _set_attribute
    el.set(convert_name(name), value)
  File "lxml.etree.pyx", line 699, in lxml.etree._Element.set (lxml-2.3/src/lxml/lxml.etree.c:34531)
  File "apihelpers.pxi", line 563, in lxml.etree._setAttributeValue (lxml-2.3/src/lxml/lxml.etree.c:15781)
  File "apihelpers.pxi", line 1366, in lxml.etree._utf8 (lxml-2.3/src/lxml/lxml.etree.c:22211)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

```

So no subtitles are downloaded, any idea ?

**Comment by ThomasClemenceau** [comment]
Seems to appear on certains episodes (don't know why). Example for Better Call Saul :
No problem for the episode 3 of the season 4, but the problem appears on the episode 4

**Comment by pannal** [comment]
That looks really bad. You might want to consider adding a separate library with only a couple of files to see whether it works there.

The ValueError stems from the special characters in your library name - could you set SZ's logging verbosity to DEBUG, then trigger a refresh on an item so I can see where that issue occurs?

I'd like to get the new release out asap.

**Comment by ThomasClemenceau** [comment]
Finally, I think tvsubtitles just doesn't know my tv show, and it appears only when opensubtitles doesn't find a sub.

The ValueError did not appears again.
In case of you want my logs anyway (there is couple of errors inside) :
https://drive.google.com/file/d/1GbNd77TEwvEQuGsisZIt477E2ZHQl8G7/view?usp=sharing

**Comment by pannal** [comment]
OK, that doesn't look too bad. And you're most likely right about TVSubtitles.

**Comment by ThomasClemenceau** [comment]
Ok, I investigated and found that SubZero doesn't recognized the rls-group of this subtitle https://www.opensubtitles.org/en/subtitles/7717928/the-magicians-the-4-1-1-fr
So the score is not the correct one

**Comment by pannal** [comment]
Yes, you want to separate the release group with a dash - nothing else should use a dash but spaces, underscores or dots. I'm guessing `The Magicians (2015).S04E11.The 4-1-1.WEBDL.1080p-Cookiemonster` might work.

**Comment by pannal** [comment]
Although a quick test shows it correctly identifies the properties:
```
For: The Magicians (2015).S04E11.The 4-1-1.WEBDL-1080p-Cookiemonster
GuessIt found: {
    "title": "The Magicians",
    "year": 2015,
    "season": 4,
    "episode": 11,
    "episode_title": "The 4-1-1",
    "format": "WEB-DL",
    "screen_size": "1080p",
    "release_group": "Cookiemonster",
    "type": "episode"
}
```

In order to investigate this further I'd need a DEBUG log from a refresh of that particular file.

**Comment by ThomasClemenceau** [comment]
[Logs_190417_13-41-04.zip](https://github.com/pannal/Sub-Zero.bundle/files/3089385/Logs_190417_13-41-04.zip)

Here it is.
I added Sonarr on Sub-Zero so no need to rename the files now (i think).

**Comment by ThomasClemenceau** [comment]
Here it is : 

[Logs_190417_13-42-55.zip](https://github.com/pannal/Sub-Zero.bundle/files/3089388/Logs_190417_13-42-55.zip)

(I have added Sonarr in SubZero settings, so I think there is no need to rename now)

**Comment by pannal** [comment]
Yes, that is to be expected. I've had a look at the subtitle on OS you're talking about - the base name doesn't fit our release group or format, which causes it not to match.

Sadly we don't have access to the alternative names at that stage (`The Magicians (2016) - 04x11 - The 4-1-1.Cookiemonster.French.C.updated.Addic7ed.com.srt`), as far as I can remember.

You'd have to manually download that subtitle using the SZ menu.

**Comment by ThomasClemenceau** [comment]
Oh I see, that's sad

Where can I find a tutorial to do it so ?

**Comment by pannal** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/Media
https://github.com/pannal/Sub-Zero.bundle/wiki/Actions
https://github.com/pannal/Sub-Zero.bundle/wiki/List
