### ISSUE TITLE
IOError: Connection lost or timed out during API request

### ISSUE THREAD

**Issue by Groumy** [pannal/Sub-Zero.bundle#653]
HI

I try to use SubZero to get some subtiltes from Addic7ed, but it won't work. It the log I always get a `IOError: Connection lost or timed out during API request` error.

I configured the captcha service to `deathbycaptcha.com`. I use a VPN and configured my DNS entries accordingly. I tried to change the timeout to `60`, but it doesn't seem to be taken into account.

Base on my `deathbycaptcha.com` account information, no captcha were resolved, so the API call is not completed,

Heres the log excerpt from a force refresh on a specific episode.

```
2019-06-16 10:29:39,865 (2d1c) :  DEBUG (logkit:13) - Force refresh intended.
2019-06-16 10:29:39,865 (2d1c) :  DEBUG (logkit:13) - Detecting streams: G:\Utorrent Completed\Agents of S.H.I.E.L.D. - S06E04 - Code Yellow.mkv, external_subtitles=False, embedded_subtitles=False
2019-06-16 10:29:39,867 (2d1c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/18793'
2019-06-16 10:29:39,878 (2d1c) :  DEBUG (logkit:13) - Couldn't detect embedded audio stream language: None
2019-06-16 10:29:39,880 (2d1c) :  DEBUG (logkit:13) - Known metadata subtitles: set([])
2019-06-16 10:29:39,881 (2d1c) :  DEBUG (logkit:13) - Known embedded subtitles: []
2019-06-16 10:29:39,891 (2d1c) :  DEBUG (logkit:13) - subzero.video: Parsing video: Agents of S.H.I.E.L.D. - S06E04 - Code Yellow.mkv, hints: {'episode_title': 'Code Yellow ', 'type': 'episode', 'title': "Marvel's Agents of S.H.I.E.L.D."}
2019-06-16 10:29:39,891 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Determining basic video properties for 'Agents of S.H.I.E.L.D. - S06E04 - Code Yellow.mkv' in 'G:\\Utorrent Completed'
2019-06-16 10:29:39,913 (2d1c) :  DEBUG (logkit:13) - subliminal_patch.core: GuessIt found: {
    "title": "Agents of S H.I.E.L.D.", 
    "season": 6, 
    "episode": 4, 
    "episode_title": "Code Yellow", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
2019-06-16 10:29:39,930 (2d1c) :  DEBUG (logkit:13) - subliminal_patch.core: Size is 937065115
2019-06-16 10:29:39,944 (2d1c) :  DEBUG (logkit:13) - subliminal_patch.core: Computed hashes {'opensubtitles': 'c304e86df99da746'}
2019-06-16 10:29:39,944 (2d1c) :  INFO (logkit:16) - Found audio streams: fr
2019-06-16 10:29:39,966 (2d1c) :  INFO (datakit:131) - Saved the dictionary file
2019-06-16 10:29:39,966 (2d1c) :  DEBUG (logkit:13) - Task data cleared: MissingSubtitles
2019-06-16 10:29:39,967 (2d1c) :  DEBUG (logkit:13) - Waiting 2 seconds until continuing
2019-06-16 10:29:41,970 (2d1c) :  INFO (logkit:16) - Agents of S.H.I.E.L.D. - S06E04 - Code Yellow.mkv has missing languages: set([<Language [fr]>])
2019-06-16 10:29:41,973 (2d1c) :  INFO (logkit:16) - subzero.video: Adding stream video_codec info: h264
2019-06-16 10:29:41,973 (2d1c) :  INFO (logkit:16) - subzero.video: Adding stream resolution info: 1080p
2019-06-16 10:29:41,973 (2d1c) :  INFO (logkit:16) - subzero.video: Adding stream audio_codec info: AAC
2019-06-16 10:29:41,974 (2d1c) :  INFO (logkit:16) - subzero.video: Adding PMS year info: 2013
2019-06-16 10:29:41,974 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Refining video with sz_tvdb
2019-06-16 10:29:41,976 (2d1c) :  INFO (logkit:16) - subliminal.refiners.tvdb: Searching series u'Agents of S H.I.E.L.D.'
2019-06-16 10:29:41,977 (2d1c) :  WARNING (logkit:19) - subliminal.refiners.tvdb: No results for series
2019-06-16 10:29:41,979 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Refining video with sz_omdb
2019-06-16 10:29:41,980 (2d1c) :  WARNING (logkit:19) - subliminal.refiners.omdb: No results for series
2019-06-16 10:29:41,980 (2d1c) :  INFO (logkit:16) - subzero.video: Using filename: Agents of S.H.I.E.L.D. - S06E04 - Code Yellow.mkv
2019-06-16 10:29:41,982 (2d1c) :  INFO (logkit:16) - subzero.video: Adding PMS title/original_title info: Marvel's Agents of S.H.I.E.L.D.
2019-06-16 10:29:41,982 (2d1c) :  INFO (logkit:16) - subzero.video: Re-refining with series title: 'Marvel's Agents of S.H.I.E.L.D.' instead of 'Agents of S H.I.E.L.D.'
2019-06-16 10:29:41,983 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Refining video with sz_tvdb
2019-06-16 10:29:41,983 (2d1c) :  INFO (logkit:16) - subliminal.refiners.tvdb: Searching series "Marvel's Agents of S.H.I.E.L.D."
2019-06-16 10:29:41,986 (2d1c) :  DEBUG (logkit:13) - subliminal.refiners.tvdb: Found 2 results
2019-06-16 10:29:41,986 (2d1c) :  DEBUG (logkit:13) - subliminal.refiners.tvdb: Found exact match on series u"Marvel's Agents of S.H.I.E.L.D."
2019-06-16 10:29:41,989 (2d1c) :  DEBUG (logkit:13) - subliminal.refiners.tvdb: Found series {u'seriesId': u'183210', u'rating': u'TV-14', u'overview': u"Agent Phil Coulson, seen in action in Marvel's The Avengers, assembles a team of top S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) agents to investigate bizarre threats.", u'firstAired': u'2013-09-24', u'id': 263365, u'aliases': [u'Agent of S.H.I.E.L.D.', u'Agents of S.H.I.E.L.D.', u'Agents of Shield', u"Marvel's Agents of S.H.I.E.L.D.: Slingshot", u'Marvels Agents of S.H.I.E.L.D.', u'S.H.I.E.L.D.', u'Shield'], u'networkId': u'', u'network': u'ABC (US)', u'zap2itId': u'SH01739244', u'seriesName': u"Marvel's Agents of S.H.I.E.L.D.", u'status': u'Continuing', u'added': u'2012-10-18 04:09:20', u'imdbId': u'tt2364582', u'lastUpdated': 1560628620, u'addedBy': 277741, u'genre': [u'Action', u'Drama', u'Mystery', u'Science-Fiction'], u'banner': u'graphical/5c828cbcca1a7.jpg', u'slug': u'marvels-agents-of-shield', u'airsTime': u'8:00 PM', u'siteRatingCount': 273, u'airsDayOfWeek': u'Friday', u'runtime': u'45', u'siteRating': 8.5}
2019-06-16 10:29:41,990 (2d1c) :  INFO (logkit:16) - subliminal.refiners.tvdb: Getting series episode 6x4
2019-06-16 10:29:41,993 (2d1c) :  DEBUG (logkit:13) - subliminal.refiners.tvdb: Found episode {u'seriesId': 263365, u'airsAfterSeason': None, u'dvdEpisodeNumber': 4, u'productionCode': u'', u'overview': u'Yo-Yo and Keller take things public; parasitic aliens threaten the human race; and someone really needs boba\u2026', u'airedSeasonID': 772489, u'thumbAdded': u'2019-06-01 00:14:46', u'episodeName': u'Code Yellow ', u'airedSeason': 6, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 6935406, u'dvdDiscid': u'', u'filename': u'episodes/263365/6935406.jpg', u'dvdSeason': 6, u'writers': [u'Lilla Zuckerman', u'Nora Zuckerman'], u'airedEpisodeNumber': 4, u'absoluteNumber': 0, u'thumbHeight': u'225', u'imdbId': u'tt8416910', u'lastUpdated': 1560029450, u'director': u'|Mark Kolpack|', u'lastUpdatedBy': 467281, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 490185, u'siteRatingCount': 2, u'directors': [u'Mark Kolpack'], u'firstAired': u'2019-05-31', u'guestStars': [], u'siteRating': 8, u'thumbWidth': u'400'}
2019-06-16 10:29:41,994 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Refining video with sz_omdb
2019-06-16 10:29:41,994 (2d1c) :  DEBUG (logkit:13) - subliminal.refiners.omdb: No need to search
2019-06-16 10:29:42,006 (2d1c) :  DEBUG (logkit:13) - Download best subtitles using settings: min_score: 240, hearing_impaired: don't prefer, languages: set([<Language [fr]>])
2019-06-16 10:29:42,010 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Using 2 threads for 2 providers (['opensubtitles', 'addic7ed'])
2019-06-16 10:29:42,010 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Downloading best subtitles for <Episode [u"Marvel's Agents of S.H.I.E.L.D.", 2013, 6x4]>
2019-06-16 10:29:42,016 (3d3c) :  INFO (logkit:16) - subliminal_patch.core: Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
2019-06-16 10:29:42,016 (3d3c) :  INFO (logkit:16) - subliminal_patch.core: Initializing provider addic7ed
2019-06-16 10:29:42,019 (3d3c) :  DEBUG (logkit:13) - subliminal_patch.providers.addic7ed: Addic7ed: using random user agents
2019-06-16 10:29:42,019 (3d3c) :  INFO (logkit:16) - subliminal_patch.providers.addic7ed: Addic7ed: Logging in
2019-06-16 10:29:42,022 (3d3c) :  DEBUG (logkit:13) - subliminal_patch.http: DNS: Using www.addic7ed.com=46.105.102.174 from cache
2019-06-16 10:29:42,424 (3d3c) :  INFO (logkit:16) - subliminal_patch.providers.addic7ed: Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often
2019-06-16 10:29:42,428 (3d3c) :  ERROR (logkit:22) - subliminal_patch.core: Unexpected error in provider 'addic7ed': Traceback (most recent call last):
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\core.py", line 99, in __getitem__
    provider.initialize()
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\providers\addic7ed.py", line 120, in initialize
    result = pitcher.throw()
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\pitcher.py", line 84, in throw
    data = self._throw()
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\subliminal_patch\pitcher.py", line 213, in _throw
    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\deathbycaptcha.py", line 203, in decode
    uploaded_captcha = self.upload(captcha, **kwargs)
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\deathbycaptcha.py", line 476, in upload
    response = self._call('upload', data)
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\deathbycaptcha.py", line 414, in _call
    self._call('login', self.userpwd.copy())
  File "C:\Users\groum\AppData\Local\Plex Media Server\Plug-ins\Sub-Zero.bundle\Contents\Libraries\Shared\deathbycaptcha.py", line 432, in _call
    raise IOError('Connection lost or timed out during API request')
IOError: Connection lost or timed out during API request

2019-06-16 10:29:42,661 (2d1c) :  INFO (logkit:16) - subliminal_patch.core: Discarding provider addic7ed
```

**Comment by pannal** [comment]
This might just be a temporary issue by DeatByCaptcha. Is this still happening?

**Comment by pannal** [comment]
Otherwise I'd suspect the VPN solution and/or the DNS in question.
