### ISSUE TITLE
Titlovi provider doesn't get disabled

### ISSUE THREAD

**Issue by EnorMOZ** [pannal/Sub-Zero.bundle#658]
`<provider.titlovi.enabled>false</provider.titlovi.enabled>`

> 2019-07-24 15:41:41,231 - com.plexapp.agents.subzero       (7fe594ff9700) :  INFO (logger:38) - subliminal_patch.core: Skipping provider 'titlovi': no language to search for
2019-07-24 15:41:50,098 - com.plexapp.agents.subzero       (7fe58bfff700) :  INFO (logger:38) - subliminal_patch.core: Listing subtitles with provider 'titlovi' and languages set([<Language [en]>])
2019-07-24 15:41:50,101 - com.plexapp.agents.subzero       (7fe58bfff700) :  INFO (logger:38) - subliminal_patch.providers.titlovi: Searching subtitles {'s': 121, 'prijevod': u'house hunters international', 'e': 2, 'g': 2006, 'jezik': 'English'}
2019-07-24 15:41:50,384 - com.plexapp.agents.subzero       (7fe58bfff700) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'titlovi': Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/titlovi.py", line 303, in list_subtitles
    video=video)]
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/titlovi.py", line 181, in query
    r = self.session.get(self.search_url, params=params, timeout=10)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 222, in get
    return self.retry_method("get", *args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 217, in retry_method
    socket.timeout))
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 57, in request
    return super(TimeoutSession, self).request(method, url, *args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 158, in request
    ret = self._request(method, url, *args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/http.py", line 113, in _request
    pitcher = pitchers.get_pitcher()("cf: %s" % domain, resp.request.url, site_key,
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/pitcher.py", line 33, in get_pitcher
    raise Exception("AntiCaptcha class not given, exiting")
Exception: AntiCaptcha class not given, exiting
2019-07-24 15:41:50,466 - com.plexapp.agents.subzero       (7fe6257fb700) :  INFO (logger:38) - subliminal_patch.core: Discarding provider titlovi

**Comment by pannal** [comment]
This is weird. Can you post your full settings xml (with masked credentials of course)

**Comment by pannal** [comment]
Are you perhaps using `advanced_settings.json`?

**Comment by EnorMOZ** [comment]
Not sure what happened but after several configurations changes and plex restarts I am not seeing the issue anymore. False alarm for now......

**Comment by pannal** [comment]
OK :)
