### ISSUE TITLE
Not getting any subtitles

### ISSUE THREAD

**Issue by Vndtt** [pannal/Sub-Zero.bundle#659]
I'm running plex on a synology DS118. I think that I have everything configured right, as to where my poor understanding gets, but theres no way that SZ download a single sub. Heres a log of Today
[com.plexapp.agents.subzero (1).log](https://github.com/pannal/Sub-Zero.bundle/files/3488576/com.plexapp.agents.subzero.1.log)

Any help will be apreciated

**Comment by Tetsunjin** [comment]
Hello.
I am stuck with the same issue but on Plex Web server. I have just downloaded the latest release of Sub-Zero today and installed it manually on Plex Web Server but when I open a movie Sub-Zero doesn't download any subtitles. I have checked my settings but I think also everything is right however I have not opensubtitle account set because I think Sub-Zero may be able to download subtitle without having personal account, isn't it?

**Comment by Vndtt** [comment]
After some investigation, I'm aware tha SZ only acivates for one of my libraries, only one of my plex shared folders

**Comment by viking1304** [comment]
Have you managed to solve this?

You need to enable SubZero for both Movies and Shows in Agents section of your Plex server settings.

**Comment by Vndtt** [comment]
As a matter of fact, after updating to the latest version of plex SZ has disapeared from the agents section. It's on the plug ins folder of my NAs' plex folder, but wont show

**Comment by pannal** [comment]
Is it inside the correct Plug-Ins folder?

**Comment by viking1304** [comment]
@Vndtt SZ works on latest Plex v1.16.5.1488, but in order to access plugin settings, you need to find it first, inside your Plex settings. It is last one, inside Managed part of your server settings. Agents is positioned little above, inside Settings part of your server settings.

[url=https://postimg.cc/WqbhQ5CS][img]https://i.postimg.cc/br1kSMTX/plex.jpg[/img][/url](url)

**Comment by plittlefield** [comment]
+1

I am not getting any subtitles from SZ on either 

I have joined 3 of the subtitles web sites and configured SZ in the Plex web app.

Where are logs so that I can show them here?

Plex Pass Lifetime
PMS Version 1.16.5.1488
SZ 2.6.5.3124 (manual install)
Ubuntu Linux 14.04.6 LTS

**Comment by pannal** [comment]
@plittlefield see Wiki.

**Comment by plittlefield** [comment]
OK, I've found the log for SZ and it seems to be failing on OpenSubtitles username and password.

I checked the details, by logging in to the OpenSubtitles web site in another browser tab and then pasting that exact info to the SZ settings pop-up.

I tried a manual refresh of a movie and it still complained...

> 2019-08-23 22:27:27,304 (7f10857fa700) :  ERROR (logger:34) - subliminal_patch.providers.opensubtitles: Login failed, please check your credentials
2019-08-23 22:27:27,429 (7f10857fa700) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'opensubtitles': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 239, in list_subtitles
    also_foreign=self.also_foreign)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 270, in query
    lambda: self.retry(lambda: checked(lambda: self.server.SearchSubtitles(self.token, criteria)))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 160, in use_token_or_login
    self.log_in()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 147, in log_in
    lambda: checked(
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/mixins.py", line 46, in retry
    return f()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 148, in <lambda>
    lambda: self.server.LogIn(self.username, self.password, 'eng',
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/opensubtitles.py", line 371, in checked
    raise Unauthorized
Unauthorized

...so I am stumped on that one!

I am also getting errors about subscene max retries, unrar not found, DNS failures and a host of others.

Overall, pretty ugly... so I have disabled SZ on the Agents and switched back to Plex Movie - which ofcourse found the subtitles straight away.

Where do I start debugging this?!

(and more importantly where do I find the time...)

:-)

**Comment by pannal** [comment]
@plittlefield this is a separate issue, please open a second ticket.
Also please post your logs zipped, so I can investigate.

Judging from the snippet you've posted, this isn't the actual issue, as it's dated `2019-08-23 22:27`, so two days ago.
