### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by mouzzampk2014** [pannal/Sub-Zero.bundle#701]
Hi, not sure if I'm missing but I cannot find notifications. Thank you

**Comment by pannal** [comment]
What exactly do you mean?

**Comment by mouzzampk2014** [comment]
> What exactly do you mean?

When sub zero download subtitles it sent notification to pushover or discord.

**Comment by pannal** [comment]
Can you elaborate? What exactly do you not find? You can configure an executable that gets called when an action occurs - using that you can do whatever you like, pushover, what ever.

I'd search in tickets in here or on the forum, people have posted their scripts.

**Comment by mouzzampk2014** [comment]
> Can you elaborate? What exactly do you not find? You can configure an executable that gets called when an action occurs - using that you can do whatever you like, pushover, what ever.
> I'd search in tickets in here or on the forum, people have posted their scripts.

Basically I am looking for when I subzero downloaded any subtitle then also sent notification to pushover or discord. 
I look for previous tickets but my big butterfly eyes couldn't see anything. If you have link that would be great. If I find it I will update you.
Thanks again

**Comment by ukdtom** [comment]
https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration

Search for `Call this executable upon successful subtitle download`

**Comment by mouzzampk2014** [comment]
> https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration
> Search for Call this executable upon successful subtitle download

I tried last night but Sub-Zero downloaded subs but I didn't received any notifications. I attached the picture. Thank you

![2](https://user-images.githubusercontent.com/44548525/69008274-9294be80-0940-11ea-8bb7-0203c3045cf4.jpg)

**Comment by ukdtom** [comment]
Okay, since I'm not even using SZ :-) , I'll step out of this, but when leaving this to the @pannal I'll simply add, that you need to add the SZ logs, since this could be related to a rights issue

**Comment by mouzzampk2014** [comment]
Hi, apologise for extremely late reply.  Currently the script is inside `/shares/Public/downloads/pushovernotify.sh %(subtitle_language)s %(filename)s %(provider)s %(score)s` and I cannot see subzero is calling the script. I am definitely missing something. Need little bit here. Thank you

I removed the existing subtitle and find the new sub and there is nothing in the logs saying script was called except bsplayer down

```2020-10-31 20:49:07,334 (-4cf50b90) :  ERROR (logger:34) - subliminal_patch.core: Unexpected error in provider 'bsplayer': Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 98, in __getitem__
    provider = provider_registry[name](**self.provider_configs.get(name, {}))
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/bsplayer.py", line 64, in __init__
    self.initialize()
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/bsplayer.py", line 70, in initialize
    self.login()
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/bsplayer.py", line 115, in login
    params=('<username></username>'
  File "/mnt/HD/HD_a2/Nas_Prog/plex_conf/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/bsplayer.py", line 106, in api_request
    raise Exception('Too many tries...')
Exception: Too many tries...``
