### ISSUE TITLE
Sub-zero not working for PlexMediaServer-1.18.5.2309 ?

### ISSUE THREAD

**Issue by jsjcjsjc** [pannal/Sub-Zero.bundle#714]
hello
I have two questions here:
1. I have install Sub-Zero for PlexMediaServer-1.18.5.2309， and made a simple configuration(only the Subtitle languag and opensubtitles VIP account). but after "Refresh All Metadata" there is nothing happend
2.so i try to check the log of Sub-Zero in the plex Channel , but it looks plex disable the Channel  on plex interface ?

 Any tips? 

Thank you so much in advance 
[Plex Media Server Logs_2020-02-02_10-22-51.zip](https://github.com/pannal/Sub-Zero.bundle/files/4143471/Plex.Media.Server.Logs_2020-02-02_10-22-51.zip)

**Comment by pannal** [comment]
- the logs don't include Sub-Zero logs
- https://github.com/pannal/Sub-Zero.bundle/issues/655

**Comment by jsjcjsjc** [comment]
> * the logs don't include Sub-Zero logs (there's a subfolder inside the Logs folder that has plugins)
> * #655

Thanks for your reply
here is the right logs .
[Desktop.zip](https://github.com/pannal/Sub-Zero.bundle/files/4143680/Desktop.zip)

And is that mean Kitana is the future of Sub-Zero ?

**Comment by jsjcjsjc** [comment]
> * the logs don't include Sub-Zero logs (there's a subfolder inside the Logs folder that has plugins)
> * #655

I have install Kitana on my QNAP NAS, it look good.
so I can use Sub-Zero interface now and get the log file.

But i don't know why it still no work...
could you please help me on it ?
[Logs_200202_17-51-16.zip](https://github.com/pannal/Sub-Zero.bundle/files/4143767/Logs_200202_17-51-16.zip)

**Comment by pannal** [comment]
Many files don't seem to have enough data in their filenames in order for SZ to process them:
```
2020-02-02 10:19:16,864 (7f069ee6b700) :  WARNING (scanning:142) - File could not be guessed: /share/CACHEDEV3_DATA/disk3/download/tv/爱情公寓/辣味英雄传/爱情公寓番外篇辣味英雄传01.mkv: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 123, in prepare_video
    providers=providers)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/video.py", line 60, in parse_video
    skip_hashing=skip_hashing, hash_from=hash_from)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 522, in scan_video
    video = Video.fromguess(path, guessed_result)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/video.py", line 170, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

I can't read Chinese, so I don't know what `爱情公寓番外篇辣味英雄传01.mkv` is.

Also for subscene and titlovi to work you have to supply username/password.

**Comment by pannal** [comment]
It would help if you would set SZ's log level to DEBUG (at the bottom of SZ's settings), then refreshing the metadata of one item, wait a minute, then re-post the logs.

**Comment by jsjcjsjc** [comment]
> It would help if you would set SZ's log level to DEBUG (at the bottom of SZ's settings), then refreshing the metadata of one item, wait a minute, then re-post the logs.

Hello Pannal
[Logs_200203_13-35-39.zip](https://github.com/pannal/Sub-Zero.bundle/files/4146419/Logs_200203_13-35-39.zip)

I set SZ's log level to DEBUG and made a test here:
there are chinese subtitles for TV on opensubtitles.org：
https://www.opensubtitles.org/en/ssearch/sublanguageid-chi/idmovie-11018
Then i choose Browse all items-> Refresh and Auto-find subtitles in Sub-Zero.

But It looks there is nothing happend,I only made a simple configuration(only the Subtitle languag and opensubtitles VIP account)， is that ok ?
Thanks in advance
here is the log

**Comment by pannal** [comment]
Judging from your Logs SZ downloaded a whole bunch of subtitles for Entourage.

**Comment by jsjcjsjc** [comment]
> Judging from your Logs SZ downloaded a whole bunch of subtitles for Entourage.

english subtitles or chinese ?
I have check plex and movies folder, there is no chinese subtitles
![plex](https://user-images.githubusercontent.com/23775256/73704997-a4138880-472f-11ea-86f4-9e4284b5e05f.jpg)
![folder](https://user-images.githubusercontent.com/23775256/73704998-a4138880-472f-11ea-8f14-c3e5b94bb188.jpg)
![zero](https://user-images.githubusercontent.com/23775256/73705000-a4ac1f00-472f-11ea-8bd8-44932b07a91b.jpg)

**Comment by pannal** [comment]
Are there any subtitles in that language on your enabled providers?
