### ISSUE TITLE
How to handle "Insufficient data to process the guess"?

### ISSUE THREAD

**Issue by wsegatto** [pannal/Sub-Zero.bundle#739]
Hi!

I am new here, I couldn't find other related issues or FAQ item.
I would like to know what to do in case I get a "Insufficient data to process the guess" message. What are my options, besides the obvious "download by yourself and add the file manually"? 
I understand an exact match was not found, but we know sometimes the major issue one will have by "borrowing" subtitles from other releases is an offset which can be easily corrected.
Anything I can do with SZ? Maybe a tag? Accepting a more general search so I'm not left with no subtitles at all?
Here's a sample log:

2020-06-28 11:04:40,308 (-57700ba0) :  INFO (logger:38) - subliminal_patch.core: Determining basic video properties for 'Battlestar.Galactica.(2003).S04.E11.1080p.Bluray.AAC.5.1.x265-LION[UTR].mkv' in '/home/pi/Videos/Plex Library/TV Shows/Battlestar Galactica Complete Bluray 1080p x265/Battlestar Galactica (2003) Season 04 S04 1080p Bluray 10bit AAC 5.1 x265 HEVC-LION[UTR]'
2020-06-28 11:04:40,557 (-57700ba0) :  DEBUG (logger:28) - subliminal_patch.core: GuessIt found: {
    "other": "Complete", 
    "format": "BluRay", 
    "screen_size": "1080p", 
    "video_codec": "h265", 
    "title": "Battlestar Galactica (2003)", 
    "season": 4, 
    "video_profile": "10bit", 
    "audio_codec": "AAC", 
    "audio_channels": "5.1", 
    "release_group": "LION", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
2020-06-28 11:04:40,561 (-57700ba0) :  WARNING (scanning:142) - File could not be guessed: /home/pi/Videos/Plex Library/TV Shows/Battlestar Galactica Complete Bluray 1080p x265/Battlestar Galactica (2003) Season 04 S04 1080p Bluray 10bit AAC 5.1 x265 HEVC-LION[UTR]/Battlestar.Galactica.(2003).S04.E11.1080p.Bluray.AAC.5.1.x265-LION[UTR].mkv: Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 123, in prepare_video
    providers=providers)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/video.py", line 60, in parse_video
    skip_hashing=skip_hashing, hash_from=hash_from)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 523, in scan_video
    video = Video.fromguess(path, guessed_result)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/video.py", line 170, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

Thanks!
Will

**Comment by morpheus65535** [comment]
Guessit cannot parse the episode number from your file name. Remove the dot between S04 and E11 and you should be good.

BTW, sub-zero is using an old version of Guessit. Latest works fine with your naming:

```
GuessIt found: {
    "title": "Battlestar Galactica",
    "year": 2003,
    "season": 4,
    "episode": 11,
    "screen_size": "1080p",
    "source": "Blu-ray",
    "audio_codec": "AAC",
    "audio_channels": "5.1",
    "video_codec": "H.265",
    "release_group": "LION[UTR]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```
