### ISSUE TITLE
SZ downloading only one subtitle when doing "refresh" or "auto-find subtitle" for whole series

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Sub-Zero.bundle#747]
I three seasons of Arrow and I accidentally deleted their existing subtitles. So I go into Katana and try to do a "refresh" and/or "auto-find subtitle" but all it did was to download a sub for one episode. Why is this? I even have addic7ed (w/ anti-captcha setup) as one of my sub providers. Won't doing these consider all episodes in that series even though they are older?

**Comment by kevindd992002** [comment]
@pannal, here are three recent debug log files if you need them: https://www.dropbox.com/s/7xcv5fwcb894oto/PMS%20Plugin%20Logs.zip?dl=0

**Comment by pannal** [comment]
I'm seeing multiple of those:
```WARNING (scanning:142) - File could not be guessed: /data/tvshows/Arrow (2012)/Season 06/Arrow (2012) - S06E19 - The Dragon - [Bluray-1080p Remux] [DTS-HD MA 5.1ch] [AVC 8bit] - [EPSiLON].mkv: Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/scanning.py", line 123, in prepare_video
    providers=providers)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subzero/video.py", line 60, in parse_video
    skip_hashing=skip_hashing, hash_from=hash_from)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 489, in scan_video
    raise ValueError('Path does not exist')
ValueError: Path does not exist
```

That might be the cause of this. Do they actually exist in exactly that way?
