### ISSUE TITLE
JsonDecodeError at Supersubtitles provider

### ISSUE THREAD

**Issue by sugarman402** [pannal/Sub-Zero.bundle#778]
When Subzero tries to parse with the supersubtitle provider, it fails with _**JSONDecodeError: Expecting value: line 1 column 1 (char 0)**_
It started couple days ago.
I'm using **SubZero 2.6.5.3268** and **Plex 1.25.2.5319** on an Ubuntu 16.04 LTS. Tried with different plex and Subzero versions but  the outcome was always the same.

```
2021-12-27 17:18:11,238 (-4e011270) :  INFO (logger:30) - subliminal_patch.core: Skipping provider 'wizdom': no language to search for
2021-12-27 17:18:11,240 (-4df06270) :  INFO (logger:30) - subliminal_patch.core: Initializing provider bsplayer
2021-12-27 17:18:11,242 (-4e034270) :  INFO (logger:30) - subliminal_patch.providers.hosszupuska: Getting the page for episode 7
2021-12-27 17:18:11,246 (-4dee3270) :  INFO (logger:30) - subliminal_patch.core: Initializing provider podnapisi
2021-12-27 17:18:11,249 (-4df06270) :  INFO (logger:30) - subliminal_patch.providers.bsplayer: Sending request: logIn.
2021-12-27 17:18:11,250 (-4dec0270) :  DEBUG (logger:28) - subliminal_patch.http: DNS: Resolved www.feliratok.info to 91.146.167.138 using [u'1.1.1.1', u'8.8.8.8']
2021-12-27 17:18:11,260 (-4e034270) :  INFO (logger:30) - subliminal_patch.providers.hosszupuska: Url http://hosszupuskasub.com/sorozatok.php?cim=Better+Call+Saul&evad=01&resz=07&nyelvtipus=%25&x=24&y=8
2021-12-27 17:18:11,263 (-4dee3270) :  INFO (logger:30) - subliminal_patch.providers.podnapisi: Searching subtitles {'sTE': 7, 'sXML': 1, 'sL': 'hu', 'sY': 2015, 'sK': u'better call saul', 'sTS': 1}
2021-12-27 17:18:11,270 (-4e034270) :  DEBUG (logger:28) - subliminal_patch.http: DNS: Using hosszupuskasub.com=172.67.158.13 from cache
2021-12-27 17:18:11,277 (-4dee3270) :  DEBUG (logger:28) - subliminal_patch.http: DNS: Using podnapisi.net=91.185.203.249 from cache
2021-12-27 17:18:11,371 (-4df06270) :  DEBUG (logger:28) - subliminal_patch.http: DNS: Resolved s107.api.bsplayer-subtitles.com to 136.243.64.117 using [u'1.1.1.1', u'8.8.8.8']
2021-12-27 17:18:11,473 (-4dee3270) :  DEBUG (logger:28) - subliminal_patch.http: DNS: Using www.podnapisi.net=91.185.203.249 from cache
2021-12-27 17:18:11,522 (-4dec0270) :  ERROR (logger:38) - subliminal_patch.core: Unexpected error in provider 'supersubtitles': Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 164, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 364, in list_subtitles
    subs = self.query(title, video=video)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 245, in query
    series_id = self.find_id(series, year, series)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/supersubtitles.py", line 207, in find_id
    results = r.json()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2021-12-27 17:18:11,524 (-4dec0270) :  INFO (config:987) - Throttling supersubtitles for 10 minutes, until 21/12/27 17:28, because of: JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)'
2021-12-27 17:18:11,539 (-4dec0270) :  INFO (datakit:131) - Saved the dictionary file
```

Some other log entries about the environment.

```
2021-12-27 17:12:26,103 (-48049450) :  DEBUG (menu:381) - ----- Environment -----
2021-12-27 17:12:26,104 (-48049450) :  DEBUG (menu:382) - Platform: Linux-i386
2021-12-27 17:12:26,105 (-48049450) :  DEBUG (menu:383) - OS: Linux
2021-12-27 17:12:26,106 (-48049450) :  DEBUG (menu:384) - Python: 2.7.17
2021-12-27 17:12:26,107 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR: /var/lib/plexmediaserver/Library/Application Support
2021-12-27 17:12:26,108 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_HOME: /usr/lib/plexmediaserver
2021-12-27 17:12:26,109 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_INFO_DEVICE: PC
2021-12-27 17:12:26,110 (-48049450) :  DEBUG (menu:392) - PLEXBUNDLEDEXTS: 1
2021-12-27 17:12:26,111 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_INFO_MODEL: i686
2021-12-27 17:12:26,112 (-48049450) :  DEBUG (menu:392) - PLEXSERVERPORT: 32400
2021-12-27 17:12:26,113 (-48049450) :  DEBUG (menu:392) - PLEXLOCALAPPDATA: /var/lib/plexmediaserver/Library/Application Support
2021-12-27 17:12:26,113 (-48049450) :  DEBUG (menu:392) - PLEXTOKEN: xxxxxxxxxxxxxxxxxxx
2021-12-27 17:12:26,114 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION: 16.04.7 LTS (Xenial Xerus)
2021-12-27 17:12:26,115 (-48049450) :  DEBUG (menu:392) - SZ_USER_AGENT: Sub-Zero/2.6.5.3268
2021-12-27 17:12:26,116 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_INFO_VENDOR: Ubuntu
2021-12-27 17:12:26,117 (-48049450) :  DEBUG (menu:392) - PLEXBUNDLEDPLUGINSPATH: /usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277
2021-12-27 17:12:26,118 (-48049450) :  DEBUG (menu:392) - PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS: 6
2021-12-27 17:12:26,119 (-48049450) :  DEBUG (menu:393) - Locale: ('hu_HU', 'UTF-8')
2021-12-27 17:12:26,122 (-48049450) :  DEBUG (menu:394) - -----------------------
2021-12-27 17:12:26,124 (-48049450) :  DEBUG (menu:396) - Setting log-level to DEBUG
2021-12-27 17:12:26,125 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: subliminal
2021-12-27 17:12:26,126 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: subliminal_patch
2021-12-27 17:12:26,127 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: enzyme
2021-12-27 17:12:26,128 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: guessit
2021-12-27 17:12:26,129 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: subzero
2021-12-27 17:12:26,130 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: libfilebot
2021-12-27 17:12:26,132 (-48049450) :  DEBUG (logger:7) - Registering LoggerHandler for dependency: cloudscraper
2021-12-27 17:12:26,133 (-48049450) :  DEBUG (__init__:72) - Sub-Zero 2.6.5.3268
2021-12-27 17:12:26,135 (-48049450) :  DEBUG (runtime:1117) - Created a thread named 'scheduler_worker'
2021-12-27 17:12:26,136 (-48049450) :  DEBUG (runtime:1117) - Created a thread named 'queue_worker'
2021-12-27 17:12:26,138 (-48049450) :  DEBUG (runtime:1117) - Created a thread named 'start'
2021-12-27 17:12:26,143 (-48049450) :  INFO (core:611) - Started plug-in
2021-12-27 17:12:26,145 (-48049450) :  DEBUG (socketinterface:160) - Starting socket server
2021-12-27 17:12:26,149 (-48049450) :  DEBUG (runtime:1117) - Created a thread named 'start'
2021-12-27 17:12:26,151 (-48049450) :  INFO (socketinterface:184) - Socket server started on port 40637
2021-12-27 17:12:26,155 (-48049450) :  INFO (pipeinterface:25) - Entering run loop
2021-12-27 17:12:26,157 (-48049450) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2021-12-27 17:12:26,168 (-48049450) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2021-12-27 17:12:26,174 (-48049450) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 449 bytes
2021-12-27 17:14:42,490 (-4c44b270) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjBzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTUKbnM4CnBhcmVudElEczQyCmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiOi8vNzQyMDU%40bGFuZz1lbnM0Cmd1aWRiMXM1CmZvcmNlczI2CmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiczEzCnByaW1hcnlfYWdlbnRzNQozNjA4NHMyCmlkcjAK
2021-12-27 17:14:42,568 (-4c44b270) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjBzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTUKbnM4CnBhcmVudElEczQyCmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiOi8vNzQyMDU@bGFuZz1lbnM0Cmd1aWRiMXM1CmZvcmNlczI2CmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiczEzCnByaW1hcnlfYWdlbnRzNQozNjA4NHMyCmlkcjAK
2021-12-27 17:14:42,570 (-4c44b270) :  INFO (agentkit:961) - Searching for matches for {'id': '36084', 'guid': 'com.plexapp.agents.thetvdb://74205?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.thetvdb', 'parentID': None}
2021-12-27 17:14:42,572 (-4c44b270) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/36084/tree'
2021-12-27 17:14:42,657 (-4c44b270) :  DEBUG (accessor:68) - Creating a new read-only model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2021-12-27 17:14:42,685 (-4c44b270) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.thetvdb://74205?lang=en
2021-12-27 17:14:42,693 (-4c44b270) :  DEBUG (model:234) - Deserializing from /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Metadata/TV Shows/5/6e0d25d41f6cde96fed18afd826dccf9285cea0.bundle/Contents/com.plexapp.agents.thetvdb/Info.xml
2021-12-27 17:14:42,719 (-4c841270) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjBzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTUKbnM4CnBhcmVudElEczQzCmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiOi8vMzIzMTY4P2xhbmc9ZW5zNApndWlkYjFzNQpmb3JjZXMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMwpwcmltYXJ5X2FnZW50czUKMzYyNThzMgppZHIwCg__
2021-12-27 17:14:42,734 (-4c841270) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.subzero/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjBzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTUKbnM4CnBhcmVudElEczQzCmNvbS5wbGV4YXBwLmFnZW50cy50aGV0dmRiOi8vMzIzMTY4P2xhbmc9ZW5zNApndWlkYjFzNQpmb3JjZXMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMwpwcmltYXJ5X2FnZW50czUKMzYyNThzMgppZHIwCg__
2021-12-27 17:14:42,740 (-4c841270) :  INFO (agentkit:961) - Searching for matches for {'id': '36258', 'guid': 'com.plexapp.agents.thetvdb://323168?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.thetvdb', 'parentID': None}
2021-12-27 17:14:42,744 (-4c841270) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/36258/tree'
2021-12-27 17:14:42,813 (-4c44b270) :  DEBUG (__init__:117) - Sub-Zero 2.6.5.3268, series search
2021-12-27 17:14:42,821 (-4c44b270) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2021-12-27 17:14:42,822 (-4c44b270) :  DEBUG (runtime:924) - Response: [200] str, 600 bytes
```

**Comment by sugarman402** [comment]
It was an issue on the supersubtitle's side, they disabled the json output.

**Comment by sugarman402** [comment]
It was an issue on the supersubtitle's side, they disabled the json output.
